package se.springboot.sharitytest.model;
// Generated Feb 28, 2023, 7:05:30 PM by Hibernate Tools 5.6.3.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.springframework.web.multipart.MultipartFile;


/**
 * Activity generated by hbm2java
 */
public class Activity implements java.io.Serializable {

	private Integer activityId;
	private User user;
	private String nameActivity;
	private String detail;
	private String place;
	private int numberPeople;
	private Date dateOpen;
	private Date dateActivity;
	private String status;
	private Set joinActivities = new HashSet(0);
	private Set comments = new HashSet(0);
	private Set conditionOfActivities = new HashSet(0);
	private Set typeOfActivities = new HashSet(0);
	private Set<MultipartFile> imageActivities = new HashSet<>(0);

	public Activity() {
	}

	public Activity(User user, String nameActivity, String detail, String place, int numberPeople, Date dateOpen,
			Date dateActivity) {
		this.user = user;
		this.nameActivity = nameActivity;
		this.detail = detail;
		this.place = place;
		this.numberPeople = numberPeople;
		this.dateOpen = dateOpen;
		this.dateActivity = dateActivity;
	}

	public Activity(User user, String nameActivity, String detail, String place, int numberPeople, Date dateOpen,
			Date dateActivity, String status, Set joinactivities, Set comments, Set conditionofactivities,
			Set typeofactivities, Set<MultipartFile> imageactivities) {
		this.user = user;
		this.nameActivity = nameActivity;
		this.detail = detail;
		this.place = place;
		this.numberPeople = numberPeople;
		this.dateOpen = dateOpen;
		this.dateActivity = dateActivity;
		this.status = status;
		this.joinActivities = joinactivities;
		this.comments = comments;
		this.conditionOfActivities = conditionofactivities;
		this.typeOfActivities = typeofactivities;
		this.imageActivities = imageactivities;
	}

	public Integer getActivityId() {
		return this.activityId;
	}

	public void setActivityId(Integer activityId) {
		this.activityId = activityId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getNameActivity() {
		return this.nameActivity;
	}

	public void setNameActivity(String nameActivity) {
		this.nameActivity = nameActivity;
	}

	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	public int getNumberPeople() {
		return this.numberPeople;
	}

	public void setNumberPeople(int numberPeople) {
		this.numberPeople = numberPeople;
	}

	public Date getDateOpen() {
		return this.dateOpen;
	}

	public void setDateOpen(Date dateOpen) {
		this.dateOpen = dateOpen;
	}

	public Date getDateActivity() {
		return this.dateActivity;
	}

	public void setDateActivity(Date dateActivity) {
		this.dateActivity = dateActivity;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set getJoinActivities() {
		return this.joinActivities;
	}

	public void setJoinActivities(Set joinactivities) {
		this.joinActivities = joinactivities;
	}

	public Set getComments() {
		return this.comments;
	}

	public void setComments(Set comments) {
		this.comments = comments;
	}

	public Set getConditionOfActivities() {
		return this.conditionOfActivities;
	}

	public void setConditionOfActivities(Set conditionofactivities) {
		this.conditionOfActivities = conditionofactivities;
	}

	public Set getTypeOfActivities() {
		return this.typeOfActivities;
	}

	public void setTypeOfActivities(Set typeofactivities) {
		this.typeOfActivities = typeofactivities;
	}

	public Set<MultipartFile> getImageActivities() {
		return this.imageActivities;
	}

	public void setImageActivities(Set<MultipartFile> imageactivities) {
		this.imageActivities = imageactivities;
	}
}
