package se.springboot.sharitytest.model;
// Generated Mar 10, 2023, 12:04:42 AM by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Conditionactivity generated by hbm2java
 */
public class ConditionActivity implements java.io.Serializable {

	private Integer conditionId;
	private String conditionDetail;
	private Set conditionOfActivities = new HashSet(0);
	private Set joinActivities = new HashSet(0);

	public ConditionActivity() {
	}

	public ConditionActivity(String conditionDetail) {
		this.conditionDetail = conditionDetail;
	}

	public ConditionActivity(String conditionDetail, Set conditionofactivities, Set joinactivities) {
		this.conditionDetail = conditionDetail;
		this.conditionOfActivities = conditionofactivities;
		this.joinActivities = joinactivities;
	}

	public Integer getConditionId() {
		return this.conditionId;
	}

	public void setConditionId(Integer conditionId) {
		this.conditionId = conditionId;
	}

	public String getConditionDetail() {
		return this.conditionDetail;
	}

	public void setConditionDetail(String conditionDetail) {
		this.conditionDetail = conditionDetail;
	}

	public Set getConditionOfActivities() {
		return this.conditionOfActivities;
	}

	public void setConditionOfActivities(Set conditionofactivities) {
		this.conditionOfActivities = conditionofactivities;
	}

	public Set getJoinActivities() {
		return this.joinActivities;
	}

	public void setJoinActivities(Set joinactivities) {
		this.joinActivities = joinactivities;
	}

}
