package se.springboot.sharitytest.model;
// Generated Feb 23, 2023, 5:00:50 PM by Hibernate Tools 5.6.3.Final

/**
 * Conditionofactivity generated by hbm2java
 */
public class ConditionOfActivity implements java.io.Serializable {

	private Integer conditionOfActivityId;
	private Activity activity;
	private ConditionActivity conditionActivity;
	private int numberPeopleInCondition;

	public ConditionOfActivity() {
	}

	public ConditionOfActivity(Activity activity, ConditionActivity conditionActivity, int numberPeopleInCondition) {
		this.activity = activity;
		this.conditionActivity = conditionActivity;
		this.numberPeopleInCondition = numberPeopleInCondition;
	}

	public Integer getConditionOfActivityId() {
		return this.conditionOfActivityId;
	}

	public void setConditionOfActivityId(Integer conditionOfActivityId) {
		this.conditionOfActivityId = conditionOfActivityId;
	}

	public Activity getActivity() {
		return this.activity;
	}

	public void setActivity(Activity activity) {
		this.activity = activity;
	}

	public ConditionActivity getConditionActivity() {
		return this.conditionActivity;
	}

	public void setConditionActivity(ConditionActivity conditionActivity) {
		this.conditionActivity = conditionActivity;
	}

	public int getNumberPeopleInCondition() {
		return this.numberPeopleInCondition;
	}

	public void setNumberPeopleInCondition(int numberPeopleInCondition) {
		this.numberPeopleInCondition = numberPeopleInCondition;
	}

}
