package se.springboot.sharitytest.model;
// Generated Feb 23, 2023, 5:00:50 PM by Hibernate Tools 5.6.3.Final

/**
 * Typeofactivity generated by hbm2java
 */
public class TypeOfActivity implements java.io.Serializable {

	private Integer typeOfActivityId;
	private Activity activity;
	private TypeActivity typeActivity;

	public TypeOfActivity() {
	}

	public TypeOfActivity(Activity activity, TypeActivity typeActivity) {
		this.activity = activity;
		this.typeActivity = typeActivity;
	}

	public Integer getTypeOfActivityId() {
		return this.typeOfActivityId;
	}

	public void setTypeOfActivityId(Integer typeOfActivityId) {
		this.typeOfActivityId = typeOfActivityId;
	}

	public Activity getActivity() {
		return this.activity;
	}

	public void setActivity(Activity activity) {
		this.activity = activity;
	}

	public TypeActivity getTypeActivity() {
		return this.typeActivity;
	}

	public void setTypeActivity(TypeActivity typeActivity) {
		this.typeActivity = typeActivity;
	}

}
