package se.springboot.sharitytest.model;
// Generated Feb 23, 2023, 5:00:50 PM by Hibernate Tools 5.6.3.Final

/**
 * Userreport generated by hbm2java
 */
public class UserReport implements java.io.Serializable {

	private Integer reportId;
	private User userByUserIdReport;
	private User userByUserIdInReport;
	private String detail;

	public UserReport() {
	}

	public UserReport(User userByUserIdReport, User userByUserIdInReport, String detail) {
		this.userByUserIdReport = userByUserIdReport;
		this.userByUserIdInReport = userByUserIdInReport;
		this.detail = detail;
	}

	public Integer getReportId() {
		return this.reportId;
	}

	public void setReportId(Integer reportId) {
		this.reportId = reportId;
	}

	public User getUserByUserIdReport() {
		return this.userByUserIdReport;
	}

	public void setUserByUserIdReport(User userByUserIdReport) {
		this.userByUserIdReport = userByUserIdReport;
	}

	public User getUserByUserIdInReport() {
		return this.userByUserIdInReport;
	}

	public void setUserByUserIdInReport(User userByUserIdInReport) {
		this.userByUserIdInReport = userByUserIdInReport;
	}

	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

}
