package se.springboot.sharitytest.model;
// Generated Feb 23, 2023, 5:00:50 PM by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Typeactivity generated by hbm2java
 */
public class TypeActivity implements java.io.Serializable {

	private Integer typeId;
	private String typeName;
	private Set typeOfActivities = new HashSet(0);

	public TypeActivity() {
	}

	public TypeActivity(String typeName) {
		this.typeName = typeName;
	}

	public TypeActivity(String typeName, Set typeofactivities) {
		this.typeName = typeName;
		this.typeOfActivities = typeofactivities;
	}

	public Integer getTypeId() {
		return this.typeId;
	}

	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public Set getTypeOfActivities() {
		return this.typeOfActivities;
	}

	public void setTypeOfActivities(Set typeofactivities) {
		this.typeOfActivities = typeofactivities;
	}

}
