package project.soa.boardgame.cafe.boardgamecafe.model;
// Generated Apr 5, 2023, 12:47:56 AM by Hibernate Tools 5.6.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Boardgamerental generated by hbm2java
 */
public class BoardgameRental implements java.io.Serializable {

	private Integer boardgamerentalId;
	private Date datestart;
	private Date dateend;
	private String name;
	private String tel;
	@JsonIgnore
	private Set boardgamerenteds = new HashSet(0);

	public BoardgameRental() {
	}

	public BoardgameRental(Date datestart, Date dateend, String name, String tel) {
		this.datestart = datestart;
		this.dateend = dateend;
		this.name = name;
		this.tel = tel;
	}

	public BoardgameRental(Date datestart, Date dateend, String name, String tel, Set boardgamerenteds) {
		this.datestart = datestart;
		this.dateend = dateend;
		this.name = name;
		this.tel = tel;
		this.boardgamerenteds = boardgamerenteds;
	}

	public Integer getBoardgamerentalId() {
		return this.boardgamerentalId;
	}

	public void setBoardgamerentalId(Integer boardgamerentalId) {
		this.boardgamerentalId = boardgamerentalId;
	}

	public Date getDatestart() {
		return this.datestart;
	}

	public void setDatestart(Date datestart) {
		this.datestart = datestart;
	}

	public Date getDateend() {
		return this.dateend;
	}

	public void setDateend(Date dateend) {
		this.dateend = dateend;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public Set getBoardgamerenteds() {
		return this.boardgamerenteds;
	}

	public void setBoardgamerenteds(Set boardgamerenteds) {
		this.boardgamerenteds = boardgamerenteds;
	}

}
