package project.soa.boardgame.cafe.boardgamecafe.model;
// Generated Apr 5, 2023, 12:47:56 AM by Hibernate Tools 5.6.3.Final

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Boardgamebought generated by hbm2java
 */
public class BoardgameBought implements java.io.Serializable {

	private Integer boardgameboughtId;
	@JsonIgnore
	private Boardgame boardgame;
	@JsonIgnore
	private BuyBoardgame buyBoardgame;

	public BoardgameBought() {
	}

	public BoardgameBought(Boardgame boardgame, BuyBoardgame buyBoardgame) {
		this.boardgame = boardgame;
		this.buyBoardgame = buyBoardgame;
	}

	public Integer getBoardgameboughtId() {
		return this.boardgameboughtId;
	}

	public void setBoardgameboughtId(Integer boardgameboughtId) {
		this.boardgameboughtId = boardgameboughtId;
	}

	public Boardgame getBoardgame() {
		return this.boardgame;
	}

	public void setBoardgame(Boardgame boardgame) {
		this.boardgame = boardgame;
	}

	public BuyBoardgame getBuyboardgame() {
		return this.buyBoardgame;
	}

	public void setBuyboardgame(BuyBoardgame buyBoardgame) {
		this.buyBoardgame = buyBoardgame;
	}

}
