package project.soa.boardgame.cafe.boardgamecafe.model;
// Generated Apr 5, 2023, 12:47:56 AM by Hibernate Tools 5.6.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Booking generated by hbm2java
 */
public class Booking implements java.io.Serializable {

	private Integer bookingId;
	@JsonIgnore
	private Table table;
	private int numberbooking;
	private Date date;
	private String name;
	private String note;
	private String tel;
	@JsonIgnore
	private Set reservedgameboards = new HashSet(0);

	public Booking() {
	}

	public Booking(Table table, int numberbooking, Date date, String name, String note, String tel) {
		this.table = table;
		this.numberbooking = numberbooking;
		this.date = date;
		this.name = name;
		this.note = note;
		this.tel = tel;
	}

	public Booking(Table table, int numberbooking, Date date, String name, String note, String tel,
			Set reservedgameboards) {
		this.table = table;
		this.numberbooking = numberbooking;
		this.date = date;
		this.name = name;
		this.note = note;
		this.tel = tel;
		this.reservedgameboards = reservedgameboards;
	}

	public Integer getBookingId() {
		return this.bookingId;
	}

	public void setBookingId(Integer bookingId) {
		this.bookingId = bookingId;
	}

	public Table getTable() {
		return this.table;
	}

	public void setTable(Table table) {
		this.table = table;
	}

	public int getNumberbooking() {
		return this.numberbooking;
	}

	public void setNumberbooking(int numberbooking) {
		this.numberbooking = numberbooking;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public Set getReservedgameboards() {
		return this.reservedgameboards;
	}

	public void setReservedgameboards(Set reservedgameboards) {
		this.reservedgameboards = reservedgameboards;
	}

}
