package project.soa.boardgame.cafe.boardgamecafe.model;
// Generated Apr 5, 2023, 12:47:56 AM by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Menu generated by hbm2java
 */
public class Menu implements java.io.Serializable {

	private Integer menuId;
	private String name;
	private float price;
	private String type;
	private String imgPath;
	@JsonIgnore
	private Set manubookings = new HashSet(0);

	public Menu() {
	}

	public Menu(String name, float price, String type) {
		this.name = name;
		this.price = price;
		this.type = type;
	}

	public Menu(String name, float price, String type, String imgPath, Set manubookings) {
		this.name = name;
		this.price = price;
		this.type = type;
		this.imgPath = imgPath;
		this.manubookings = manubookings;
	}

	public Integer getMenuId() {
		return this.menuId;
	}

	public void setMenuId(Integer menuId) {
		this.menuId = menuId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getImgPath() {
		return this.imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

	public Set getManubookings() {
		return this.manubookings;
	}

	public void setManubookings(Set manubookings) {
		this.manubookings = manubookings;
	}

}
