package org.cassava.model;
// Generated Nov 30, 2022, 10:33:28 PM by Hibernate Tools 5.5.9.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Api generated by hbm2java
 */
public class Api implements java.io.Serializable {

	private Integer apiId;
	private String name;
	private List<ApiStaff> apistaffs = new ArrayList<ApiStaff>();
	private List<ApiDetail> apidetails = new ArrayList<ApiDetail>();

	public Api() {
	}

	public Api(String name) {
		this.name = name;
	}

	public Api(String name, List apistaffs, List apidetails) {
		this.name = name;
		this.apistaffs = apistaffs;
		this.apidetails = apidetails;
	}

	public Integer getApiId() {
		return this.apiId;
	}

	public void setApiId(Integer apiId) {
		this.apiId = apiId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public List<ApiStaff> getApistaffs() {
		return this.apistaffs;
	}

	public void setApistaffs(List apistaffs) {
		this.apistaffs = apistaffs;
	}

	public List<ApiDetail> getApidetails() {
		return this.apidetails;
	}

	public void setApidetails(List apidetails) {
		this.apidetails = apidetails;
	}

}
