package org.cassava.model;
// Generated Nov 30, 2022, 10:33:28 PM by Hibernate Tools 5.5.9.Final

/**
 * Apidetail generated by hbm2java
 */
public class ApiDetail implements java.io.Serializable {

	private Integer apiDetailId;
	private Api api;
	private String name;

	public ApiDetail() {
	}

	public ApiDetail(Api api, String name) {
		this.api = api;
		this.name = name;
	}

	public Integer getApiDetailId() {
		return this.apiDetailId;
	}

	public void setApiDetailId(Integer apiDetailId) {
		this.apiDetailId = apiDetailId;
	}

	public Api getApi() {
		return this.api;
	}

	public void setApi(Api api) {
		this.api = api;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
