package org.cassava.model;
// Generated Nov 30, 2022, 10:33:28 PM by Hibernate Tools 5.5.9.Final

import java.util.Date;

/**
 * Apistaff generated by hbm2java
 */
public class ApiStaff implements java.io.Serializable {

	private Integer apiStaffId;
	private Api api;
	private Staff staff;
	private Date expireDate;

	public ApiStaff() {
	}

	public ApiStaff(Api api, Staff staff, Date expireDate) {
		this.api = api;
		this.staff = staff;
		this.expireDate = expireDate;
	}

	public Integer getApiStaffId() {
		return this.apiStaffId;
	}

	public void setApiStaffId(Integer apiStaffId) {
		this.apiStaffId = apiStaffId;
	}

	public Api getApi() {
		return this.api;
	}

	public void setApi(Api api) {
		this.api = api;
	}

	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	public Date getExpireDate() {
		return this.expireDate;
	}

	public void setExpireDate(Date expireDate) {
		this.expireDate = expireDate;
	}

}
