package org.cassava.model;
// Generated Nov 30, 2022, 10:33:28 PM by Hibernate Tools 5.5.9.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Disease generated by hbm2java
 * @param <E>
 */
public class Disease implements java.io.Serializable {

	private int diseaseId;
	@JsonIgnore
	private Plant plant;
	@JsonIgnore
	private TargetOfSurvey targetofsurvey;
	@NotNull (message = "ห้ามไม่มีค่า")
	@NotBlank(message = "ห้ามเว้นว่าง")
	@Size(max = 10, message = "ต้องมีความยาวไม่เกิน 10 ตัวอักษร")
	private String code;
	@NotNull (message = "ห้ามไม่มีค่า")
	@NotBlank(message = "ห้ามเว้นว่าง")
	@Size(max = 150, message = "ต้องมีความยาวไม่เกิน 150 ตัวอักษร")
	private String symptom;
	private String controlDisease;
	private String controlPest;
	@NotNull (message = "ห้ามไม่มีค่า")
	@NotBlank(message = "ห้ามเว้นว่าง")
	@Size(max = 255, message = "ต้องมีความยาวไม่เกิน 255 ตัวอักษร")
	private String source;
	@JsonIgnore
	private List<Pathogen> pathogens = new ArrayList<Pathogen>();
	@JsonIgnore
	private List<Pest> pests = new ArrayList<Pest>();
	@JsonIgnore
	private List<ImgDisease> imgdiseases = new ArrayList<ImgDisease>();

	public Disease() {
	}

	public Disease(Plant plant, TargetOfSurvey targetofsurvey) {
		this.plant = plant;
		this.targetofsurvey = targetofsurvey;
	}

	public Disease(Plant plant, TargetOfSurvey targetofsurvey, String code, String symptom, String controlDisease,
			String controlPest, String source, List pathogens, List pests, List imgdiseases) {
		this.plant = plant;
		this.targetofsurvey = targetofsurvey;
		this.code = code;
		this.symptom = symptom;
		this.controlDisease = controlDisease;
		this.controlPest = controlPest;
		this.source = source;
		this.pathogens = pathogens;
		this.pests = pests;
		this.imgdiseases = imgdiseases;
	}

	public int getDiseaseId() {
		return this.diseaseId;
	}

	public void setDiseaseId(int diseaseId) {
		this.diseaseId = diseaseId;
	}

	public Plant getPlant() {
		return this.plant;
	}

	public void setPlant(Plant plant) {
		this.plant = plant;
	}

	public TargetOfSurvey getTargetofsurvey() {
		return this.targetofsurvey;
	}

	public void setTargetofsurvey(TargetOfSurvey targetofsurvey) {
		this.targetofsurvey = targetofsurvey;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getSymptom() {
		return this.symptom;
	}

	public void setSymptom(String symptom) {
		this.symptom = symptom;
	}

	public String getControlDisease() {
		return this.controlDisease;
	}

	public void setControlDisease(String controlDisease) {
		this.controlDisease = controlDisease;
	}

	public String getControlPest() {
		return this.controlPest;
	}

	public void setControlPest(String controlPest) {
		this.controlPest = controlPest;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public List<Pathogen> getPathogens() {
		return this.pathogens;
	}

	public void setPathogens(List pathogens) {
		this.pathogens = pathogens;
	}

	public List<Pest> getPests() {
		return this.pests;
	}

	public void setPests(List pests) {
		this.pests = pests;
	}

	public List<ImgDisease> getImgdiseases() {
		return this.imgdiseases;
	}

	public void setImgdiseases(List imgdiseases) {
		this.imgdiseases = imgdiseases;
	}

}
