package org.cassava.model;
// Generated Nov 30, 2022, 10:33:28 PM by Hibernate Tools 5.5.9.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * District generated by hbm2java
 */
public class District implements java.io.Serializable {

	private Integer districtId;
	@JsonIgnore
	private Province province;
	private String name;
	private String code;
	@JsonIgnore
	private List<Subdistrict> subdistricts = new ArrayList<Subdistrict>();

	public District() {
	}

	public District(Province province, String name) {
		this.province = province;
		this.name = name;
	}

	public District(Province province, String name, String code, List subdistricts) {
		this.province = province;
		this.name = name;
		this.code = code;
		this.subdistricts = subdistricts;
	}

	public Integer getDistrictId() {
		return this.districtId;
	}

	public void setDistrictId(Integer districtId) {
		this.districtId = districtId;
	}

	public Province getProvince() {
		return this.province;
	}

	public void setProvince(Province province) {
		this.province = province;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public List<Subdistrict> getSubdistricts() {
		return this.subdistricts;
	}

	public void setSubdistricts(List subdistricts) {
		this.subdistricts = subdistricts;
	}

}
