package org.cassava.model;
// Generated Nov 30, 2022, 10:33:28 PM by Hibernate Tools 5.5.9.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Farmer generated by hbm2java
 */
public class Farmer implements java.io.Serializable {

	private int farmerId;
	@JsonIgnore
	private Subdistrict subdistrict;
	@JsonIgnore
	private User user;
	
	private String idcard;
	@NotNull(message = "ห้ามไม่มีค่า")
	@NotBlank(message = "ห้ามเว้นว่าง")
	private String address;
	@NotNull(message = "ห้ามไม่มีค่า")
	private String pdpastatus;
	private Date pdpavalidDate;
	private String pdpafilePath;
	@JsonIgnore
	private List<Organization> organizations = new ArrayList<Organization>();

	public Farmer() {
	}

	public Farmer(User user, String address, String pdpastatus) {
		this.user = user;
		this.address = address;
		this.pdpastatus = pdpastatus;
	}
	
	public Farmer(Subdistrict subdistrict, User user, String idcard, String address, String pdpastatus,
			Date pdpavalidDate, String pdpafilePath, List organizations) {
		this.subdistrict = subdistrict;
		this.user = user;
		this.idcard = idcard;
		this.address = address;
		this.pdpastatus = pdpastatus;
		this.pdpavalidDate = pdpavalidDate;
		this.pdpafilePath = pdpafilePath;
		this.organizations = organizations;
	}

	public int getFarmerId() {
		return this.farmerId;
	}

	public void setFarmerId(int farmerId) {
		this.farmerId = farmerId;
	}

	public Subdistrict getSubdistrict() {
		return this.subdistrict;
	}

	public void setSubdistrict(Subdistrict subdistrict) {
		this.subdistrict = subdistrict;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getIdcard() {
		return this.idcard;
	}

	public void setIdcard(String idcard) {
		this.idcard = idcard;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPdpastatus() {
		return this.pdpastatus;
	}

	public void setPdpastatus(String pdpastatus) {
		this.pdpastatus = pdpastatus;
	}

	public Date getPdpavalidDate() {
		return this.pdpavalidDate;
	}

	public void setPdpavalidDate(Date pdpavalidDate) {
		this.pdpavalidDate = pdpavalidDate;
	}

	public String getPdpafilePath() {
		return this.pdpafilePath;
	}

	public void setPdpafilePath(String pdpafilePath) {
		this.pdpafilePath = pdpafilePath;
	}

	public List<Organization> getOrganizations() {
		return this.organizations;
	}

	public void setOrganizations(List organizations) {
		this.organizations = organizations;
	}

}
