package org.cassava.model;
// Generated Nov 30, 2022, 10:33:28 PM by Hibernate Tools 5.5.9.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Herbicide generated by hbm2java
 */
public class Herbicide implements java.io.Serializable {

	private Integer herbicideId;
	private String name;
	@JsonIgnore
	private List<Planting> plantingsForWeedingChemical2 = new ArrayList<Planting>();
	@JsonIgnore
	private List<Planting> plantingsForWeedingChemical1 = new ArrayList<Planting>();
	@JsonIgnore
	private List<Planting> plantingsForWeedingChemical3 = new ArrayList<Planting>();

	public Herbicide() {
	}

	public Herbicide(String name) {
		this.name = name;
	}

	public Herbicide(String name, List plantingsForWeedingChemical2, List plantingsForWeedingChemical1,
			List plantingsForWeedingChemical3) {
		this.name = name;
		this.plantingsForWeedingChemical2 = plantingsForWeedingChemical2;
		this.plantingsForWeedingChemical1 = plantingsForWeedingChemical1;
		this.plantingsForWeedingChemical3 = plantingsForWeedingChemical3;
	}

	public Integer getHerbicideId() {
		return this.herbicideId;
	}

	public void setHerbicideId(Integer herbicideId) {
		this.herbicideId = herbicideId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public List<Planting> getPlantingsForWeedingChemical2() {
		return this.plantingsForWeedingChemical2;
	}

	public void setPlantingsForWeedingChemical2(List plantingsForWeedingChemical2) {
		this.plantingsForWeedingChemical2 = plantingsForWeedingChemical2;
	}

	public List<Planting> getPlantingsForWeedingChemical1() {
		return this.plantingsForWeedingChemical1;
	}

	public void setPlantingsForWeedingChemical1(List plantingsForWeedingChemical1) {
		this.plantingsForWeedingChemical1 = plantingsForWeedingChemical1;
	}

	public List<Planting> getPlantingsForWeedingChemical3() {
		return this.plantingsForWeedingChemical3;
	}

	public void setPlantingsForWeedingChemical3(List plantingsForWeedingChemical3) {
		this.plantingsForWeedingChemical3 = plantingsForWeedingChemical3;
	}

}
