package org.cassava.model;
// Generated Nov 30, 2022, 10:33:28 PM by Hibernate Tools 5.5.9.Final

/**
 * Imgdisease generated by hbm2java
 */
public class ImgDisease implements java.io.Serializable {

	private Integer imgDiseaseId;
	private Disease disease;
	private String filePath;

	public ImgDisease() {
	}

	public ImgDisease(Disease disease, String filePath) {
		this.disease = disease;
		this.filePath = filePath;
	}

	public Integer getImgDiseaseId() {
		return this.imgDiseaseId;
	}

	public void setImgDiseaseId(Integer imgDiseaseId) {
		this.imgDiseaseId = imgDiseaseId;
	}

	public Disease getDisease() {
		return this.disease;
	}

	public void setDisease(Disease disease) {
		this.disease = disease;
	}

	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

}
