package org.cassava.model;
// Generated Nov 30, 2022, 10:33:28 PM by Hibernate Tools 5.5.9.Final

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Imgherbicidedamage generated by hbm2java
 */
public class ImgHerbicideDamage implements java.io.Serializable {

	private Integer imgHerbicideDamageId;
	@JsonIgnore
	private Survey survey;
	private User userByUploadBy;
	private User userByApproveBy;
	private String filePath;
	private String filePathS;
	private Date uploadDate;
	private String approveStatus;
	private Date approveDate;

	public ImgHerbicideDamage() {
	}

	public ImgHerbicideDamage(Survey survey, String filePath, String filePathS, Date uploadDate, String approveStatus) {
		this.survey = survey;
		this.filePath = filePath;
		this.filePathS = filePathS;
		this.uploadDate = uploadDate;
		this.approveStatus = approveStatus;
	}

	public ImgHerbicideDamage(Survey survey, User userByUploadBy, User userByApproveBy, String filePath,
			String filePathS, Date uploadDate, String approveStatus, Date approveDate) {
		this.survey = survey;
		this.userByUploadBy = userByUploadBy;
		this.userByApproveBy = userByApproveBy;
		this.filePath = filePath;
		this.filePathS = filePathS;
		this.uploadDate = uploadDate;
		this.approveStatus = approveStatus;
		this.approveDate = approveDate;
	}

	public Integer getImgHerbicideDamageId() {
		return this.imgHerbicideDamageId;
	}

	public void setImgHerbicideDamageId(Integer imgHerbicideDamageId) {
		this.imgHerbicideDamageId = imgHerbicideDamageId;
	}

	public Survey getSurvey() {
		return this.survey;
	}

	public void setSurvey(Survey survey) {
		this.survey = survey;
	}

	public User getUserByUploadBy() {
		return this.userByUploadBy;
	}

	public void setUserByUploadBy(User userByUploadBy) {
		this.userByUploadBy = userByUploadBy;
	}

	public User getUserByApproveBy() {
		return this.userByApproveBy;
	}

	public void setUserByApproveBy(User userByApproveBy) {
		this.userByApproveBy = userByApproveBy;
	}

	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	public String getFilePathS() {
		return this.filePathS;
	}

	public void setFilePathS(String filePathS) {
		this.filePathS = filePathS;
	}

	public Date getUploadDate() {
		return this.uploadDate;
	}

	public void setUploadDate(Date uploadDate) {
		this.uploadDate = uploadDate;
	}

	public String getApproveStatus() {
		return this.approveStatus;
	}

	public void setApproveStatus(String approveStatus) {
		this.approveStatus = approveStatus;
	}

	public Date getApproveDate() {
		return this.approveDate;
	}

	public void setApproveDate(Date approveDate) {
		this.approveDate = approveDate;
	}

}
