package org.cassava.model;
// Generated Nov 30, 2022, 10:33:28 PM by Hibernate Tools 5.5.9.Final

/**
 * Imgnaturalenemy generated by hbm2java
 */
public class ImgNaturalEnemy implements java.io.Serializable {

	private Integer imgNaturalEnemyId;
	private NaturalEnemy naturalenemy;
	private String filePath;

	public ImgNaturalEnemy() {
	}

	public ImgNaturalEnemy(NaturalEnemy naturalenemy, String filePath) {
		this.naturalenemy = naturalenemy;
		this.filePath = filePath;
	}

	public Integer getImgNaturalEnemyId() {
		return this.imgNaturalEnemyId;
	}

	public void setImgNaturalEnemyId(Integer imgNaturalEnemyId) {
		this.imgNaturalEnemyId = imgNaturalEnemyId;
	}

	public NaturalEnemy getNaturalenemy() {
		return this.naturalenemy;
	}

	public void setNaturalenemy(NaturalEnemy naturalenemy) {
		this.naturalenemy = naturalenemy;
	}

	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

}
