package org.cassava.model;
// Generated Nov 30, 2022, 10:33:28 PM by Hibernate Tools 5.5.9.Final

import java.util.Date;

/**
 * Imgsurveytargetpoint generated by hbm2java
 */
public class ImgSurveyTargetPoint implements java.io.Serializable {

	private Integer imgSurveyTargetPointId;
	private SurveyTargetPoint surveytargetpoint;
	private User userByApproveBy;
	private User userByUploadBy;
	private String filePath;
	private String filePathS;
	private Date uploadDate;
	private String approveStatus;
	private Date approveDate;

	public ImgSurveyTargetPoint() {
	}

	public ImgSurveyTargetPoint(SurveyTargetPoint surveytargetpoint, String filePath, String filePathS, Date uploadDate,
			String approveStatus) {
		this.surveytargetpoint = surveytargetpoint;
		this.filePath = filePath;
		this.filePathS = filePathS;
		this.uploadDate = uploadDate;
		this.approveStatus = approveStatus;
	}

	public ImgSurveyTargetPoint(SurveyTargetPoint surveytargetpoint, User userByApproveBy, User userByUploadBy,
			String filePath, String filePathS, Date uploadDate, String approveStatus, Date approveDate) {
		this.surveytargetpoint = surveytargetpoint;
		this.userByApproveBy = userByApproveBy;
		this.userByUploadBy = userByUploadBy;
		this.filePath = filePath;
		this.filePathS = filePathS;
		this.uploadDate = uploadDate;
		this.approveStatus = approveStatus;
		this.approveDate = approveDate;
	}

	public Integer getImgSurveyTargetPointId() {
		return this.imgSurveyTargetPointId;
	}

	public void setImgSurveyTargetPointId(Integer imgSurveyTargetPointId) {
		this.imgSurveyTargetPointId = imgSurveyTargetPointId;
	}

	public SurveyTargetPoint getSurveytargetpoint() {
		return this.surveytargetpoint;
	}

	public void setSurveytargetpoint(SurveyTargetPoint surveytargetpoint) {
		this.surveytargetpoint = surveytargetpoint;
	}

	public User getUserByApproveBy() {
		return this.userByApproveBy;
	}

	public void setUserByApproveBy(User userByApproveBy) {
		this.userByApproveBy = userByApproveBy;
	}

	public User getUserByUploadBy() {
		return this.userByUploadBy;
	}

	public void setUserByUploadBy(User userByUploadBy) {
		this.userByUploadBy = userByUploadBy;
	}

	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	public String getFilePathS() {
		return this.filePathS;
	}

	public void setFilePathS(String filePathS) {
		this.filePathS = filePathS;
	}

	public Date getUploadDate() {
		return this.uploadDate;
	}

	public void setUploadDate(Date uploadDate) {
		this.uploadDate = uploadDate;
	}

	public String getApproveStatus() {
		return this.approveStatus;
	}

	public void setApproveStatus(String approveStatus) {
		this.approveStatus = approveStatus;
	}

	public Date getApproveDate() {
		return this.approveDate;
	}

	public void setApproveDate(Date approveDate) {
		this.approveDate = approveDate;
	}

}
