package org.cassava.model;
// Generated Nov 30, 2022, 10:33:28 PM by Hibernate Tools 5.5.9.Final

/**
 * Imgvariety generated by hbm2java
 */
public class ImgVariety implements java.io.Serializable {

	private Integer imgVarietyId;
	private Variety variety;
	private String filePath;

	public ImgVariety() {
	}

	public ImgVariety(Variety variety, String filePath) {
		this.variety = variety;
		this.filePath = filePath;
	}

	public Integer getImgVarietyId() {
		return this.imgVarietyId;
	}

	public void setImgVarietyId(Integer imgVarietyId) {
		this.imgVarietyId = imgVarietyId;
	}

	public Variety getVariety() {
		return this.variety;
	}

	public void setVariety(Variety variety) {
		this.variety = variety;
	}

	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

}
