package org.cassava.model;

import com.fasterxml.jackson.annotation.JsonIgnore;

// Generated Nov 30, 2022, 10:33:28 PM by Hibernate Tools 5.5.9.Final

/**
 * MessagereceiverId generated by hbm2java
 */
public class MessagereceiverId implements java.io.Serializable {

	private int messageId;
	@JsonIgnore
	private int receiverId;

	public MessagereceiverId() {
	}

	public MessagereceiverId(int messageId, int receiverId) {
		this.messageId = messageId;
		this.receiverId = receiverId;
	}

	public int getMessageId() {
		return this.messageId;
	}

	public void setMessageId(int messageId) {
		this.messageId = messageId;
	}

	public int getReceiverId() {
		return this.receiverId;
	}

	public void setReceiverId(int receiverId) {
		this.receiverId = receiverId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MessagereceiverId))
			return false;
		MessagereceiverId castOther = (MessagereceiverId) other;

		return (this.getMessageId() == castOther.getMessageId()) && (this.getReceiverId() == castOther.getReceiverId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMessageId();
		result = 37 * result + this.getReceiverId();
		return result;
	}

}
