package org.cassava.model;
// Generated Nov 30, 2022, 10:33:28 PM by Hibernate Tools 5.5.9.Final

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Messagereceiver generated by hbm2java
 */
public class Messagereceiver implements java.io.Serializable {

	@JsonIgnore
	private MessagereceiverId id;
	@JsonIgnore
	private Message message;
	@JsonIgnore
	private User user;
	private String readStatus;

	public Messagereceiver() {
	}

	public Messagereceiver(MessagereceiverId id, Message message, User user, String readStatus) {
		this.id = id;
		this.message = message;
		this.user = user;
		this.readStatus = readStatus;
	}

	public MessagereceiverId getId() {
		return this.id;
	}

	public void setId(MessagereceiverId id) {
		this.id = id;
	}

	public Message getMessage() {
		return this.message;
	}

	public void setMessage(Message message) {
		this.message = message;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getReadStatus() {
		return this.readStatus;
	}

	public void setReadStatus(String readStatus) {
		this.readStatus = readStatus;
	}

}
