package org.cassava.model;
// Generated Nov 30, 2022, 10:33:28 PM by Hibernate Tools 5.5.9.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Message generated by hbm2java
 */
public class Message implements java.io.Serializable {

	@JsonIgnore
	private Integer messageId;
	@JsonIgnore
	private User user;
	@JsonIgnore
	private Date sendDate;
	private String title;
	private String text;
	private String type;
	@JsonIgnore
	private List<Messagereceiver> messagereceivers = new ArrayList<Messagereceiver>();

	public Message() {
	}

	public Message(Date sendDate) {
		this.sendDate = sendDate;
	}

	public Message(User user, Date sendDate, String title, String text, String type, List messagereceivers) {
		this.user = user;
		this.sendDate = sendDate;
		this.title = title;
		this.text = text;
		this.type = type;
		this.messagereceivers = messagereceivers;
	}

	public Integer getMessageId() {
		return this.messageId;
	}

	public void setMessageId(Integer messageId) {
		this.messageId = messageId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getSendDate() {
		return this.sendDate;
	}

	public void setSendDate(Date sendDate) {
		this.sendDate = sendDate;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public List<Messagereceiver> getMessagereceivers() {
		return this.messagereceivers;
	}

	public void setMessagereceivers(List messagereceivers) {
		this.messagereceivers = messagereceivers;
	}

}
