package org.cassava.model;
// Generated Nov 30, 2022, 10:33:28 PM by Hibernate Tools 5.5.9.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Naturalenemy generated by hbm2java
 */
public class NaturalEnemy implements java.io.Serializable {

	private int naturalEnemyId;
	@JsonIgnore
	private TargetOfSurvey targetofsurvey;
	@NotBlank(message = "ห้ามเว้นว่าง")
	@Size(min = 2, max = 50, message = "ชื่อต้องมีความยาวตั้งแต่ 2 - 50 ตัวอักษร")
	private String commonName;
	@NotBlank(message = "ห้ามเว้นว่าง")
	@Size(min = 2, max = 70, message = "ชื่อต้องมีความยาวตั้งแต่ 2 - 70 ตัวอักษร")
	private String scientificName;
	private String type;
	private String controlMethod;
	private String releaseRate;
	@NotBlank(message = "ห้ามเว้นว่าง")
	@Size(min = 2, max = 255, message = "ต้องมีความยาวตั้งแต่ 2 - 255 ตัวอักษร")
	private String source;
	@JsonIgnore
	private List<ImgNaturalEnemy> imgnaturalenemies = new ArrayList<ImgNaturalEnemy>();

	public NaturalEnemy() {
	}

	public NaturalEnemy(TargetOfSurvey targetofsurvey, String commonName, String scientificName, String source) {
		this.targetofsurvey = targetofsurvey;
		this.commonName = commonName;
		this.scientificName = scientificName;
		this.source = source;
	}

	public NaturalEnemy(TargetOfSurvey targetofsurvey, String commonName, String scientificName, String type,
			String controlMethod, String releaseRate, String source, List imgnaturalenemies) {
		this.targetofsurvey = targetofsurvey;
		this.commonName = commonName;
		this.scientificName = scientificName;
		this.type = type;
		this.controlMethod = controlMethod;
		this.releaseRate = releaseRate;
		this.source = source;
		this.imgnaturalenemies = imgnaturalenemies;
	}

	public int getNaturalEnemyId() {
		return this.naturalEnemyId;
	}

	public void setNaturalEnemyId(int naturalEnemyId) {
		this.naturalEnemyId = naturalEnemyId;
	}

	public TargetOfSurvey getTargetofsurvey() {
		return this.targetofsurvey;
	}

	public void setTargetofsurvey(TargetOfSurvey targetofsurvey) {
		this.targetofsurvey = targetofsurvey;
	}

	public String getCommonName() {
		return this.commonName;
	}

	public void setCommonName(String commonName) {
		this.commonName = commonName;
	}

	public String getScientificName() {
		return this.scientificName;
	}

	public void setScientificName(String scientificName) {
		this.scientificName = scientificName;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getControlMethod() {
		return this.controlMethod;
	}

	public void setControlMethod(String controlMethod) {
		this.controlMethod = controlMethod;
	}

	public String getReleaseRate() {
		return this.releaseRate;
	}

	public void setReleaseRate(String releaseRate) {
		this.releaseRate = releaseRate;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public List<ImgNaturalEnemy> getImgnaturalenemies() {
		return this.imgnaturalenemies;
	}

	public void setImgnaturalenemies(List imgnaturalenemies) {
		this.imgnaturalenemies = imgnaturalenemies;
	}

}
