package org.cassava.model;
// Generated Nov 30, 2022, 10:33:28 PM by Hibernate Tools 5.5.9.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Pathogentype generated by hbm2java
 */
public class PathogenType implements java.io.Serializable {

	private Integer pathogenTypeId;
	private String name;
	private List<Pathogen> pathogens = new ArrayList<Pathogen>();

	public PathogenType() {
	}

	public PathogenType(String name) {
		this.name = name;
	}

	public PathogenType(String name, List pathogens) {
		this.name = name;
		this.pathogens = pathogens;
	}

	public Integer getPathogenTypeId() {
		return this.pathogenTypeId;
	}

	public void setPathogenTypeId(Integer pathogenTypeId) {
		this.pathogenTypeId = pathogenTypeId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public List<Pathogen> getPathogens() {
		return this.pathogens;
	}

	public void setPathogens(List pathogens) {
		this.pathogens = pathogens;
	}

}
