package org.cassava.model;
// Generated Jul 19, 2023, 8:08:22 PM by Hibernate Tools 5.6.3.Final

/**
 * Permissionorganization generated by hbm2java
 */
public class PermissionOrganization implements java.io.Serializable {

	private Integer permissionOrganizationId;
	private Organization organization;
	private Permission permission;

	public PermissionOrganization() {
	}

	public PermissionOrganization(Organization organization, Permission permission) {
		this.organization = organization;
		this.permission = permission;
	}

	public Integer getPermissionOrganizationId() {
		return this.permissionOrganizationId;
	}

	public void setPermissionOrganizationId(Integer permissionOrganizationId) {
		this.permissionOrganizationId = permissionOrganizationId;
	}

	public Organization getOrganization() {
		return this.organization;
	}

	public void setOrganization(Organization organization) {
		this.organization = organization;
	}

	public Permission getPermission() {
		return this.permission;
	}

	public void setPermission(Permission permission) {
		this.permission = permission;
	}

}
