package org.cassava.model;
// Generated Nov 30, 2022, 10:33:28 PM by Hibernate Tools 5.5.9.Final

/**
 * Permissionfile generated by hbm2java
 */
public class PermissionFile implements java.io.Serializable {

	private Integer permissionFileId;
	private Permission permission;
	private String filePath;

	public PermissionFile() {
	}

	public PermissionFile(Permission permission, String filePath) {
		this.permission = permission;
		this.filePath = filePath;
	}

	public Integer getPermissionFileId() {
		return this.permissionFileId;
	}

	public void setPermissionFileId(Integer permissionFileId) {
		this.permissionFileId = permissionFileId;
	}

	public Permission getPermission() {
		return this.permission;
	}

	public void setPermission(Permission permission) {
		this.permission = permission;
	}

	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

}
