package org.cassava.model;
// Generated Nov 30, 2022, 10:33:28 PM by Hibernate Tools 5.5.9.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Permission generated by hbm2java
 */
public class Permission implements java.io.Serializable {

	private Integer permisisonId;
	private Staff staffByApproveBy;
	private Staff staffByStaffId;
	@NotNull(message = "ห้ามไม่มีค่า")
	private String type;
	@NotNull(message = "ห้ามไม่มีค่า")
	private Date dateInfoStart;
	@NotNull(message = "ห้ามไม่มีค่า")
	private Date dateInfoEnd;
	@NotNull(message = "ห้ามไม่มีค่า")
	private Date dateRequest;
	private Date dateApprove;
	private Date dateExpire;
	private String status;
	@JsonIgnore
	private List<PermissionFile> permissionfiles = new ArrayList<PermissionFile>();
	@JsonIgnore
	private List<PermissionTargetOfSurvey> permissiontargetofsurveys = new ArrayList<PermissionTargetOfSurvey>();
	@JsonIgnore
	private List<PermissionProvince> permissionprovinces = new ArrayList<PermissionProvince>();
	@JsonIgnore
	private List<PermissionOrganization> permissionOrganizations = new ArrayList<PermissionOrganization>();
	
	public Permission() {
	}

	public Permission(Staff staffByStaffId, String type, Date dateInfoStart, Date dateInfoEnd, Date dateRequest,
			String status) {
		this.staffByStaffId = staffByStaffId;
		this.type = type;
		this.dateInfoStart = dateInfoStart;
		this.dateInfoEnd = dateInfoEnd;
		this.dateRequest = dateRequest;
		this.status = status;
	}

	public Permission(Staff staffByApproveBy, Staff staffByStaffId, String type, Date dateInfoStart, Date dateInfoEnd,
			Date dateRequest, Date dateApprove, Date dateExpire, String status, List permissionfiles,
			List permissiontargetofsurveys, List permissionprovinces) {
		this.staffByApproveBy = staffByApproveBy;
		this.staffByStaffId = staffByStaffId;
		this.type = type;
		this.dateInfoStart = dateInfoStart;
		this.dateInfoEnd = dateInfoEnd;
		this.dateRequest = dateRequest;
		this.dateApprove = dateApprove;
		this.dateExpire = dateExpire;
		this.status = status;
		this.permissionfiles = permissionfiles;
		this.permissiontargetofsurveys = permissiontargetofsurveys;
		this.permissionprovinces = permissionprovinces;
	}

	public Integer getPermisisonId() {
		return this.permisisonId;
	}

	public void setPermisisonId(Integer permisisonId) {
		this.permisisonId = permisisonId;
	}

	public Staff getStaffByApproveBy() {
		return this.staffByApproveBy;
	}

	public void setStaffByApproveBy(Staff staffByApproveBy) {
		this.staffByApproveBy = staffByApproveBy;
	}

	public Staff getStaffByStaffId() {
		return this.staffByStaffId;
	}

	public void setStaffByStaffId(Staff staffByStaffId) {
		this.staffByStaffId = staffByStaffId;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Date getDateInfoStart() {
		return this.dateInfoStart;
	}

	public void setDateInfoStart(Date dateInfoStart) {
		this.dateInfoStart = dateInfoStart;
	}

	public Date getDateInfoEnd() {
		return this.dateInfoEnd;
	}

	public void setDateInfoEnd(Date dateInfoEnd) {
		this.dateInfoEnd = dateInfoEnd;
	}

	public Date getDateRequest() {
		return this.dateRequest;
	}

	public void setDateRequest(Date dateRequest) {
		this.dateRequest = dateRequest;
	}

	public Date getDateApprove() {
		return this.dateApprove;
	}

	public void setDateApprove(Date dateApprove) {
		this.dateApprove = dateApprove;
	}

	public Date getDateExpire() {
		return this.dateExpire;
	}

	public void setDateExpire(Date dateExpire) {
		this.dateExpire = dateExpire;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public List<PermissionFile> getPermissionfiles() {
		return this.permissionfiles;
	}

	public void setPermissionfiles(List permissionfiles) {
		this.permissionfiles = permissionfiles;
	}
	
	public List<PermissionTargetOfSurvey> getPermissiontargetofsurveys() {
		return this.permissiontargetofsurveys;
	}

	public void setPermissiontargetofsurveys(List permissiontargetofsurveys) {
		this.permissiontargetofsurveys = permissiontargetofsurveys;
	}

	public List<PermissionProvince> getPermissionprovinces() {
		return this.permissionprovinces;
	}

	public void setPermissionprovinces(List permissionprovinces) {
		this.permissionprovinces = permissionprovinces;
	}

	public List<PermissionOrganization> getPermissionOrganizations() {
		return permissionOrganizations;
	}

	public void setPermissionOrganizations(List<PermissionOrganization> permissionOrganizations) {
		this.permissionOrganizations = permissionOrganizations;
	}

}
