package org.cassava.model;
// Generated Nov 30, 2022, 10:33:28 PM by Hibernate Tools 5.5.9.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Pestphase generated by hbm2java
 */
public class PestPhase implements java.io.Serializable {

	private Integer pestPhaseId;
	private String name;
	private List<PestPhaseSurvey> pestphasesurveys = new ArrayList<PestPhaseSurvey>();

	public PestPhase() {
	}

	public PestPhase(String name) {
		this.name = name;
	}

	public PestPhase(String name, List pestphasesurveys) {
		this.name = name;
		this.pestphasesurveys = pestphasesurveys;
	}

	public Integer getPestPhaseId() {
		return this.pestPhaseId;
	}

	public void setPestPhaseId(Integer pestPhaseId) {
		this.pestPhaseId = pestPhaseId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public List<PestPhaseSurvey> getPestphasesurveys() {
		return this.pestphasesurveys;
	}

	public void setPestphasesurveys(List pestphasesurveys) {
		this.pestphasesurveys = pestphasesurveys;
	}

}
