package org.cassava.model;
// Generated Nov 30, 2022, 10:33:28 PM by Hibernate Tools 5.5.9.Final

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Pestmanagement generated by hbm2java
 */
public class PestManagement implements java.io.Serializable {

	private Integer pestManagementId;
	@JsonIgnore
	private Pest pest;
	@NotNull(message = "ห้ามไม่มีค่า")
	@NotBlank(message = "ห้ามเว้นว่าง")
	@Size(min = 2, max = 30, message = "ชื่อต้องมีความยาวตั้งแต่ 2 - 30 ตัวอักษร")
	private String pesticideName;
	@NotNull(message = "ห้ามไม่มีค่า")
	@NotBlank(message = "ห้ามเว้นว่าง")
	@Size(min = 2, max = 30, message = "ชื่อต้องมีความยาวตั้งแต่ 2 - 30 ตัวอักษร")
	private String pesticideNameEng;
	private String percentApi;
	@NotNull(message = "ห้ามไม่มีค่า")
	@NotBlank(message = "ห้ามเว้นว่าง")
	@Size(max = 20, message = "ต้องมีความยาวไม่เกิน 20 ตัวอักษร")
	private String pesticideMechanism;
	@NotNull(message = "ห้ามไม่มีค่า")
	@NotBlank(message = "ห้ามเว้นว่าง")
	@Size(max = 30, message = "ต้องมีความยาวไม่เกิน 32 ตัวอักษร")
	private String toxicityLevel;
	@NotNull(message = "ห้ามไม่มีค่า")
	@NotBlank(message = "ห้ามเว้นว่าง")
	@Size(max = 30, message = "ต้องมีความยาวไม่เกิน 32 ตัวอักษร")
	private String mixingRatio;
	@NotNull(message = "ห้ามไม่มีค่า")
	@NotBlank(message = "ห้ามเว้นว่าง")
	private String instruction;
	@NotNull(message = "ห้ามไม่มีค่า")
	private String instructionDetail;
	@NotNull(message = "ห้ามไม่มีค่า")
	private String note;

	public PestManagement() {
	}

	public PestManagement(Pest pest, String pesticideName, String pesticideNameEng, String percentApi,
			String pesticideMechanism, String toxicityLevel, String mixingRatio, String instruction,
			String instructionDetail, String note) {
		this.pest = pest;
		this.pesticideName = pesticideName;
		this.pesticideNameEng = pesticideNameEng;
		this.percentApi = percentApi;
		this.pesticideMechanism = pesticideMechanism;
		this.toxicityLevel = toxicityLevel;
		this.mixingRatio = mixingRatio;
		this.instruction = instruction;
		this.instructionDetail = instructionDetail;
		this.note = note;
	}

	public Integer getPestManagementId() {
		return this.pestManagementId;
	}

	public void setPestManagementId(Integer pestManagementId) {
		this.pestManagementId = pestManagementId;
	}

	public Pest getPest() {
		return this.pest;
	}

	public void setPest(Pest pest) {
		this.pest = pest;
	}

	public String getPesticideName() {
		return this.pesticideName;
	}

	public void setPesticideName(String pesticideName) {
		this.pesticideName = pesticideName;
	}

	public String getPesticideNameEng() {
		return this.pesticideNameEng;
	}

	public void setPesticideNameEng(String pesticideNameEng) {
		this.pesticideNameEng = pesticideNameEng;
	}

	public String getPercentApi() {
		return this.percentApi;
	}

	public void setPercentApi(String percentApi) {
		this.percentApi = percentApi;
	}

	public String getPesticideMechanism() {
		return this.pesticideMechanism;
	}

	public void setPesticideMechanism(String pesticideMechanism) {
		this.pesticideMechanism = pesticideMechanism;
	}

	public String getToxicityLevel() {
		return this.toxicityLevel;
	}

	public void setToxicityLevel(String toxicityLevel) {
		this.toxicityLevel = toxicityLevel;
	}

	public String getMixingRatio() {
		return this.mixingRatio;
	}

	public void setMixingRatio(String mixingRatio) {
		this.mixingRatio = mixingRatio;
	}

	public String getInstruction() {
		return this.instruction;
	}

	public void setInstruction(String instruction) {
		this.instruction = instruction;
	}

	public String getInstructionDetail() {
		return this.instructionDetail;
	}

	public void setInstructionDetail(String instructionDetail) {
		this.instructionDetail = instructionDetail;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
