package org.cassava.model;
// Generated Nov 30, 2022, 10:33:28 PM by Hibernate Tools 5.5.9.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Pest generated by hbm2java
 */
public class Pest implements java.io.Serializable {

	private Integer pestId;
	@NotNull(message = "ห้ามไม่มีค่า")
	@NotBlank(message = "ห้ามเว้นว่าง")
	@Size(min = 2, max = 30, message = "ชื่อต้องมีความยาวตั้งแต่ 2 - 30 ตัวอักษร")
	private String name;
	@NotNull(message = "ห้ามไม่มีค่า")
	@NotBlank(message = "ห้ามเว้นว่าง")
	@Size(min = 2, max = 70, message = "ชื่อต้องมีความยาวตั้งแต่ 2 - 70 ตัวอักษร")
	private String scientificName;
	@NotNull(message = "ห้ามไม่มีค่า")
	@NotBlank(message = "ห้ามเว้นว่าง")
	@Size(min = 2, max = 255, message = "ต้องมีความยาวตั้งแต่ 2 - 255 ตัวอักษร")
	private String source;
	@JsonIgnore
	private List<Disease> diseases = new ArrayList<Disease>();
	@JsonIgnore
	private List<PestManagement> pestmanagements = new ArrayList<PestManagement>();
	@JsonIgnore
	private List<PestPhaseSurvey> pestphasesurveys = new ArrayList<PestPhaseSurvey>();
	@JsonIgnore
	private List<ImgPest> imgpests = new ArrayList<ImgPest>();

	public Pest() {
	}

	public Pest(String name, String scientificName, String source) {
		this.name = name;
		this.scientificName = scientificName;
		this.source = source;
	}

	public Pest(String name, String scientificName, String source, List diseases, List pestmanagements,
			List pestphasesurveys, List imgpests) {
		this.name = name;
		this.scientificName = scientificName;
		this.source = source;
		this.diseases = diseases;
		this.pestmanagements = pestmanagements;
		this.pestphasesurveys = pestphasesurveys;
		this.imgpests = imgpests;
	}

	public Integer getPestId() {
		return this.pestId;
	}

	public void setPestId(Integer pestId) {
		this.pestId = pestId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getScientificName() {
		return this.scientificName;
	}

	public void setScientificName(String scientificName) {
		this.scientificName = scientificName;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public List<Disease> getDiseases() {
		return this.diseases;
	}

	public void setDiseases(List diseases) {
		this.diseases = diseases;
	}

	public List<PestManagement> getPestmanagements() {
		return this.pestmanagements;
	}

	public void setPestmanagements(List pestmanagements) {
		this.pestmanagements = pestmanagements;
	}

	public List<PestPhaseSurvey> getPestphasesurveys() {
		return this.pestphasesurveys;
	}

	public void setPestphasesurveys(List pestphasesurveys) {
		this.pestphasesurveys = pestphasesurveys;
	}

	public List<ImgPest> getImgpests() {
		return this.imgpests;
	}

	public void setImgpests(List imgpests) {
		this.imgpests = imgpests;
	}

}
