package org.cassava.model;
// Generated Nov 30, 2022, 10:33:28 PM by Hibernate Tools 5.5.9.Final

/**
 * Plantphase generated by hbm2java
 */
public class PlantPhase implements java.io.Serializable {

	private Integer plantPhaseId;
	private Plant plant;
	private int order;
	private String name;
	private int dayStart;
	private int dayEnd;

	public PlantPhase() {
	}

	public PlantPhase(Plant plant, int order, String name, int dayStart, int dayEnd) {
		this.plant = plant;
		this.order = order;
		this.name = name;
		this.dayStart = dayStart;
		this.dayEnd = dayEnd;
	}

	public Integer getPlantPhaseId() {
		return this.plantPhaseId;
	}

	public void setPlantPhaseId(Integer plantPhaseId) {
		this.plantPhaseId = plantPhaseId;
	}

	public Plant getPlant() {
		return this.plant;
	}

	public void setPlant(Plant plant) {
		this.plant = plant;
	}

	public int getOrder() {
		return this.order;
	}

	public void setOrder(int order) {
		this.order = order;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getDayStart() {
		return this.dayStart;
	}

	public void setDayStart(int dayStart) {
		this.dayStart = dayStart;
	}

	public int getDayEnd() {
		return this.dayEnd;
	}

	public void setDayEnd(int dayEnd) {
		this.dayEnd = dayEnd;
	}

}
