package org.cassava.model;
// Generated Nov 30, 2022, 10:33:28 PM by Hibernate Tools 5.5.9.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.validation.constraints.Digits;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Planting generated by hbm2java
 */
public class Planting implements java.io.Serializable {

	private Integer plantingId;
	@JsonIgnore
	private Field field;
	//@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	@JsonIgnore
	private Herbicide herbicideByWeedingChemical2;
	//@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	@JsonIgnore
	private Herbicide herbicideByWeedingChemical1;
	//@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	@JsonIgnore
	private Herbicide herbicideByWeedingChemical3;
	@JsonIgnore
	private User userByCreateBy;
	@JsonIgnore
	private User userByLastUpdateBy;
	@NotBlank(message = "ห้ามเว้นว่าง")
	@Size(min = 2, max = 25, message = "ต้องมีความยาวตั้งแต่ 2 - 25 ตัวอักษร")
	private String code;
	@NotBlank(message = "ห้ามเว้นว่าง")
	@Size(min = 2, max = 60, message = "ชื่อต้องมีความยาวตั้งแต่ 2 - 60 ตัวอักษร")
	private String name;
	@Digits(integer=12, fraction=6)
	private Float size;
	@NotNull(message = "ห้ามไม่มีค่า")
	private String previousPlant;
	private String previousPlantOther;
	@NotNull(message = "ห้ามไม่มีค่า")
	private String besidePlant;
	private String besidePlantOther;
	private String primaryVarietyOther;
	@NotNull(message = "ห้ามไม่มีค่า")
	private Date primaryPlantPlantingDate;
	private Date primaryPlantHarvestDate;
	private String secondaryPlantType;
	private String secondaryPlantVariety;
	private Date secondaryPlantPlantingDate;
	private Date secondaryPlantHarvestDate;
	@NotNull(message = "ห้ามไม่มีค่า")
	private String stemSource;
	@NotNull(message = "ห้ามไม่มีค่า")
	private String soakingStemChemical;
	@NotNull(message = "ห้ามไม่มีค่า")
	private String numTillage;
	@NotNull(message = "ห้ามไม่มีค่า")
	private String soilAmendments;
	private String soilAmendmentsOther;
	private Date fertilizerDate1;
	private String fertilizerFormular1;
	private Date fertilizerDate2;
	private String fertilizerFormular2;
	private Date fertilizerDate3;
	private String fertilizerFormular3;
	private String diseaseManagement;
	private String pestManagement;
	private Integer weedingMonth1;
	private String weedingChemicalOther1;
	private Integer weedingMonth2;
	private String weedingChemicalOther2;
	private Integer weedingMonth3;
	private String weedingChemicalOther3;
	@NotNull(message = "ห้ามไม่มีค่า")
	private String note;
	private Date createDate;
	private Date lastUpdateDate;

	@JsonIgnore
	private List<PlantingCassavaVariety> plantingcassavavarieties = new ArrayList<PlantingCassavaVariety>();
	public List<PlantingCassavaVariety> getPlantingcassavavarieties() {
		return plantingcassavavarieties;
	}

	public void setPlantingcassavavarieties(List<PlantingCassavaVariety> plantingcassavavarieties) {
		this.plantingcassavavarieties = plantingcassavavarieties;
	}

	@JsonIgnore
	private List<Survey> surveys = new ArrayList<Survey>();

	public Planting() {
	}

	public Planting(Field field, User userByCreateBy, String previousPlant, String besidePlant,
			Date primaryPlantPlantingDate, Date primaryPlantHarvestDate, String stemSource, String soakingStemChemical,
			String numTillage, String soilAmendments, int weedingMonth1, String note, Date createDate) {
		this.field = field;
		this.userByCreateBy = userByCreateBy;
		this.previousPlant = previousPlant;
		this.besidePlant = besidePlant;
		this.primaryPlantPlantingDate = primaryPlantPlantingDate;
		this.primaryPlantHarvestDate = primaryPlantHarvestDate;
		this.stemSource = stemSource;
		this.soakingStemChemical = soakingStemChemical;
		this.numTillage = numTillage;
		this.soilAmendments = soilAmendments;
		this.weedingMonth1 = weedingMonth1;
		this.note = note;
		this.createDate = createDate;
	}

	public Planting(Field field, Herbicide herbicideByWeedingChemical2, Herbicide herbicideByWeedingChemical1,
			Herbicide herbicideByWeedingChemical3, User userByCreateBy, User userByLastUpdateBy, String code,
			String name, Float size, String previousPlant, String previousPlantOther, String besidePlant,
			String besidePlantOther, String primaryVarietyOther, Date primaryPlantPlantingDate,
			Date primaryPlantHarvestDate, String secondaryPlantType, String secondaryPlantVariety,
			Date secondaryPlantPlantingDate, Date secondaryPlantHarvestDate, String stemSource,
			String soakingStemChemical, String numTillage, String soilAmendments, String soilAmendmentsOther,
			Date fertilizerDate1, String fertilizerFormular1, Date fertilizerDate2, String fertilizerFormular2,
			Date fertilizerDate3, String fertilizerFormular3, String diseaseManagement, String pestManagement,
			int weedingMonth1, String weedingChemicalOther1, Integer weedingMonth2, String weedingChemicalOther2,
			Integer weedingMonth3, String weedingChemicalOther3, String note, Date createDate, Date lastUpdateDate,
			List plantingcassavavarieties, List surveys) {
		this.field = field;
		this.herbicideByWeedingChemical2 = herbicideByWeedingChemical2;
		this.herbicideByWeedingChemical1 = herbicideByWeedingChemical1;
		this.herbicideByWeedingChemical3 = herbicideByWeedingChemical3;
		this.userByCreateBy = userByCreateBy;
		this.userByLastUpdateBy = userByLastUpdateBy;
		this.code = code;
		this.name = name;
		this.size = size;
		this.previousPlant = previousPlant;
		this.previousPlantOther = previousPlantOther;
		this.besidePlant = besidePlant;
		this.besidePlantOther = besidePlantOther;
		this.primaryVarietyOther = primaryVarietyOther;
		this.primaryPlantPlantingDate = primaryPlantPlantingDate;
		this.primaryPlantHarvestDate = primaryPlantHarvestDate;
		this.secondaryPlantType = secondaryPlantType;
		this.secondaryPlantVariety = secondaryPlantVariety;
		this.secondaryPlantPlantingDate = secondaryPlantPlantingDate;
		this.secondaryPlantHarvestDate = secondaryPlantHarvestDate;
		this.stemSource = stemSource;
		this.soakingStemChemical = soakingStemChemical;
		this.numTillage = numTillage;
		this.soilAmendments = soilAmendments;
		this.soilAmendmentsOther = soilAmendmentsOther;
		this.fertilizerDate1 = fertilizerDate1;
		this.fertilizerFormular1 = fertilizerFormular1;
		this.fertilizerDate2 = fertilizerDate2;
		this.fertilizerFormular2 = fertilizerFormular2;
		this.fertilizerDate3 = fertilizerDate3;
		this.fertilizerFormular3 = fertilizerFormular3;
		this.diseaseManagement = diseaseManagement;
		this.pestManagement = pestManagement;
		this.weedingMonth1 = weedingMonth1;
		this.weedingChemicalOther1 = weedingChemicalOther1;
		this.weedingMonth2 = weedingMonth2;
		this.weedingChemicalOther2 = weedingChemicalOther2;
		this.weedingMonth3 = weedingMonth3;
		this.weedingChemicalOther3 = weedingChemicalOther3;
		this.note = note;
		this.createDate = createDate;
		this.lastUpdateDate = lastUpdateDate;
		this.plantingcassavavarieties = plantingcassavavarieties;
		this.surveys = surveys;
	}
	
	public void clone(Planting other) {
		this.code = other.code;
		this.name = other.name;
		this.size = other.size;
		this.previousPlant = other.previousPlant;
		this.previousPlantOther = other.previousPlantOther;
		this.besidePlant = other.besidePlant;
		this.besidePlantOther = other.besidePlantOther;
		this.primaryVarietyOther = other.primaryVarietyOther;
		this.primaryPlantPlantingDate = other.primaryPlantPlantingDate;
		this.primaryPlantHarvestDate = other.primaryPlantHarvestDate;
		this.secondaryPlantType = other.secondaryPlantType;
		this.secondaryPlantVariety = other.secondaryPlantVariety;
		this.secondaryPlantPlantingDate = other.secondaryPlantPlantingDate;
		this.secondaryPlantHarvestDate = other.secondaryPlantHarvestDate;
		this.stemSource = other.stemSource;
		this.soakingStemChemical = other.soakingStemChemical;
		this.numTillage = other.numTillage;
		this.soilAmendments = other.soilAmendments;
		this.soilAmendmentsOther = other.soilAmendmentsOther;
		this.fertilizerDate1 = other.fertilizerDate1;
		this.fertilizerFormular1 = other.fertilizerFormular1;
		this.fertilizerDate2 = other.fertilizerDate2;
		this.fertilizerFormular2 = other.fertilizerFormular2;
		this.fertilizerDate3 = other.fertilizerDate3;
		this.fertilizerFormular3 = other.fertilizerFormular3;
		this.diseaseManagement = other.diseaseManagement;
		this.pestManagement = other.pestManagement;
		this.weedingMonth1 = other.weedingMonth1;
		this.weedingChemicalOther1 = other.weedingChemicalOther1;
		this.weedingMonth2 = other.weedingMonth2;
		this.weedingChemicalOther2 = other.weedingChemicalOther2;
		this.weedingMonth3 = other.weedingMonth3;
		this.weedingChemicalOther3 = other.weedingChemicalOther3;
		this.note = other.note;
		this.createDate = other.createDate;
		this.lastUpdateDate = other.lastUpdateDate;
	}

	public Integer getPlantingId() {
		return this.plantingId;
	}

	public void setPlantingId(Integer plantingId) {
		this.plantingId = plantingId;
	}

	public Field getField() {
		return this.field;
	}

	public void setField(Field field) {
		this.field = field;
	}

	public Herbicide getHerbicideByWeedingChemical2() {
		return this.herbicideByWeedingChemical2;
	}

	public void setHerbicideByWeedingChemical2(Herbicide herbicideByWeedingChemical2) {
		this.herbicideByWeedingChemical2 = herbicideByWeedingChemical2;
	}

	public Herbicide getHerbicideByWeedingChemical1() {
		return this.herbicideByWeedingChemical1;
	}

	public void setHerbicideByWeedingChemical1(Herbicide herbicideByWeedingChemical1) {
		this.herbicideByWeedingChemical1 = herbicideByWeedingChemical1;
	}

	public Herbicide getHerbicideByWeedingChemical3() {
		return this.herbicideByWeedingChemical3;
	}

	public void setHerbicideByWeedingChemical3(Herbicide herbicideByWeedingChemical3) {
		this.herbicideByWeedingChemical3 = herbicideByWeedingChemical3;
	}

	public User getUserByCreateBy() {
		return this.userByCreateBy;
	}

	public void setUserByCreateBy(User userByCreateBy) {
		this.userByCreateBy = userByCreateBy;
	}

	public User getUserByLastUpdateBy() {
		return this.userByLastUpdateBy;
	}

	public void setUserByLastUpdateBy(User userByLastUpdateBy) {
		this.userByLastUpdateBy = userByLastUpdateBy;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Float getSize() {
		return this.size;
	}

	public void setSize(Float size) {
		this.size = size;
	}

	public String getPreviousPlant() {
		return this.previousPlant;
	}

	public void setPreviousPlant(String previousPlant) {
		this.previousPlant = previousPlant;
	}

	public String getPreviousPlantOther() {
		return this.previousPlantOther;
	}

	public void setPreviousPlantOther(String previousPlantOther) {
		this.previousPlantOther = previousPlantOther;
	}

	public String getBesidePlant() {
		return this.besidePlant;
	}

	public void setBesidePlant(String besidePlant) {
		this.besidePlant = besidePlant;
	}

	public String getBesidePlantOther() {
		return this.besidePlantOther;
	}

	public void setBesidePlantOther(String besidePlantOther) {
		this.besidePlantOther = besidePlantOther;
	}

	public String getPrimaryVarietyOther() {
		return this.primaryVarietyOther;
	}

	public void setPrimaryVarietyOther(String primaryVarietyOther) {
		this.primaryVarietyOther = primaryVarietyOther;
	}

	public Date getPrimaryPlantPlantingDate() {
		return this.primaryPlantPlantingDate;
	}

	public void setPrimaryPlantPlantingDate(Date primaryPlantPlantingDate) {
		this.primaryPlantPlantingDate = primaryPlantPlantingDate;
	}

	public Date getPrimaryPlantHarvestDate() {
		return this.primaryPlantHarvestDate;
	}

	public void setPrimaryPlantHarvestDate(Date primaryPlantHarvestDate) {
		this.primaryPlantHarvestDate = primaryPlantHarvestDate;
	}

	public String getSecondaryPlantType() {
		return this.secondaryPlantType;
	}

	public void setSecondaryPlantType(String secondaryPlantType) {
		this.secondaryPlantType = secondaryPlantType;
	}

	public String getSecondaryPlantVariety() {
		return this.secondaryPlantVariety;
	}

	public void setSecondaryPlantVariety(String secondaryPlantVariety) {
		this.secondaryPlantVariety = secondaryPlantVariety;
	}

	public Date getSecondaryPlantPlantingDate() {
		return this.secondaryPlantPlantingDate;
	}

	public void setSecondaryPlantPlantingDate(Date secondaryPlantPlantingDate) {
		this.secondaryPlantPlantingDate = secondaryPlantPlantingDate;
	}

	public Date getSecondaryPlantHarvestDate() {
		return this.secondaryPlantHarvestDate;
	}

	public void setSecondaryPlantHarvestDate(Date secondaryPlantHarvestDate) {
		this.secondaryPlantHarvestDate = secondaryPlantHarvestDate;
	}

	public String getStemSource() {
		return this.stemSource;
	}

	public void setStemSource(String stemSource) {
		this.stemSource = stemSource;
	}

	public String getSoakingStemChemical() {
		return this.soakingStemChemical;
	}

	public void setSoakingStemChemical(String soakingStemChemical) {
		this.soakingStemChemical = soakingStemChemical;
	}

	public String getNumTillage() {
		return this.numTillage;
	}

	public void setNumTillage(String numTillage) {
		this.numTillage = numTillage;
	}

	public String getSoilAmendments() {
		return this.soilAmendments;
	}

	public void setSoilAmendments(String soilAmendments) {
		this.soilAmendments = soilAmendments;
	}

	public String getSoilAmendmentsOther() {
		return this.soilAmendmentsOther;
	}

	public void setSoilAmendmentsOther(String soilAmendmentsOther) {
		this.soilAmendmentsOther = soilAmendmentsOther;
	}

	public Date getFertilizerDate1() {
		return this.fertilizerDate1;
	}

	public void setFertilizerDate1(Date fertilizerDate1) {
		this.fertilizerDate1 = fertilizerDate1;
	}

	public String getFertilizerFormular1() {
		return this.fertilizerFormular1;
	}

	public void setFertilizerFormular1(String fertilizerFormular1) {
		this.fertilizerFormular1 = fertilizerFormular1;
	}

	public Date getFertilizerDate2() {
		return this.fertilizerDate2;
	}

	public void setFertilizerDate2(Date fertilizerDate2) {
		this.fertilizerDate2 = fertilizerDate2;
	}

	public String getFertilizerFormular2() {
		return this.fertilizerFormular2;
	}

	public void setFertilizerFormular2(String fertilizerFormular2) {
		this.fertilizerFormular2 = fertilizerFormular2;
	}

	public Date getFertilizerDate3() {
		return this.fertilizerDate3;
	}

	public void setFertilizerDate3(Date fertilizerDate3) {
		this.fertilizerDate3 = fertilizerDate3;
	}

	public String getFertilizerFormular3() {
		return this.fertilizerFormular3;
	}

	public void setFertilizerFormular3(String fertilizerFormular3) {
		this.fertilizerFormular3 = fertilizerFormular3;
	}

	public String getDiseaseManagement() {
		return this.diseaseManagement;
	}

	public void setDiseaseManagement(String diseaseManagement) {
		this.diseaseManagement = diseaseManagement;
	}

	public String getPestManagement() {
		return this.pestManagement;
	}

	public void setPestManagement(String pestManagement) {
		this.pestManagement = pestManagement;
	}

	public Integer getWeedingMonth1() {
		return this.weedingMonth1;
	}

	public void setWeedingMonth1(Integer weedingMonth1) {
		this.weedingMonth1 = weedingMonth1;
	}

	public String getWeedingChemicalOther1() {
		return this.weedingChemicalOther1;
	}

	public void setWeedingChemicalOther1(String weedingChemicalOther1) {
		this.weedingChemicalOther1 = weedingChemicalOther1;
	}

	public Integer getWeedingMonth2() {
		return this.weedingMonth2;
	}

	public void setWeedingMonth2(Integer weedingMonth2) {
		this.weedingMonth2 = weedingMonth2;
	}

	public String getWeedingChemicalOther2() {
		return this.weedingChemicalOther2;
	}

	public void setWeedingChemicalOther2(String weedingChemicalOther2) {
		this.weedingChemicalOther2 = weedingChemicalOther2;
	}

	public Integer getWeedingMonth3() {
		return this.weedingMonth3;
	}

	public void setWeedingMonth3(Integer weedingMonth3) {
		this.weedingMonth3 = weedingMonth3;
	}

	public String getWeedingChemicalOther3() {
		return this.weedingChemicalOther3;
	}

	public void setWeedingChemicalOther3(String weedingChemicalOther3) {
		this.weedingChemicalOther3 = weedingChemicalOther3;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	public List<Survey> getSurveys() {
		return this.surveys;
	}

	public void setSurveys(List surveys) {
		this.surveys = surveys;
	}

}
