package org.cassava.model;
// Generated Nov 30, 2022, 10:33:28 PM by Hibernate Tools 5.5.9.Final

/**
 * PlantingcassavavarietyId generated by hbm2java
 */
public class PlantingCassavaVarietyId implements java.io.Serializable {

	private int plantingId;
	private int varietyId;

	public PlantingCassavaVarietyId() {
	}

	public PlantingCassavaVarietyId(int plantingId, int varietyId) {
		this.plantingId = plantingId;
		this.varietyId = varietyId;
	}

	public int getPlantingId() {
		return this.plantingId;
	}

	public void setPlantingId(int plantingId) {
		this.plantingId = plantingId;
	}

	public int getVarietyId() {
		return this.varietyId;
	}

	public void setVarietyId(int varietyId) {
		this.varietyId = varietyId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PlantingCassavaVarietyId))
			return false;
		PlantingCassavaVarietyId castOther = (PlantingCassavaVarietyId) other;

		return (this.getPlantingId() == castOther.getPlantingId()) && (this.getVarietyId() == castOther.getVarietyId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPlantingId();
		result = 37 * result + this.getVarietyId();
		return result;
	}

}
