package org.cassava.model;
// Generated Nov 30, 2022, 10:33:28 PM by Hibernate Tools 5.5.9.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Plant generated by hbm2java
 */
public class Plant implements java.io.Serializable {

	private Integer plantId;
	private String name;
	private int harvestDayStart;
	private int harvestDayEnd;
	private List<Variety> varieties = new ArrayList<Variety>();
	private List<Disease> diseases = new ArrayList<Disease>();
	private List<PlantPhase> plantphases = new ArrayList<PlantPhase>();

	public Plant() {
	}

	public Plant(String name, int harvestDayStart, int harvestDayEnd) {
		this.name = name;
		this.harvestDayStart = harvestDayStart;
		this.harvestDayEnd = harvestDayEnd;
	}

	public Plant(String name, int harvestDayStart, int harvestDayEnd, List varieties, List diseases, List plantphases) {
		this.name = name;
		this.harvestDayStart = harvestDayStart;
		this.harvestDayEnd = harvestDayEnd;
		this.varieties = varieties;
		this.diseases = diseases;
		this.plantphases = plantphases;
	}

	public Integer getPlantId() {
		return this.plantId;
	}

	public void setPlantId(Integer plantId) {
		this.plantId = plantId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getHarvestDayStart() {
		return this.harvestDayStart;
	}

	public void setHarvestDayStart(int harvestDayStart) {
		this.harvestDayStart = harvestDayStart;
	}

	public int getHarvestDayEnd() {
		return this.harvestDayEnd;
	}

	public void setHarvestDayEnd(int harvestDayEnd) {
		this.harvestDayEnd = harvestDayEnd;
	}

	public List<Variety> getVarieties() {
		return this.varieties;
	}

	public void setVarieties(List varieties) {
		this.varieties = varieties;
	}

	public List<Disease> getDiseases() {
		return this.diseases;
	}

	public void setDiseases(List diseases) {
		this.diseases = diseases;
	}

	public List<PlantPhase> getPlantphases() {
		return this.plantphases;
	}

	public void setPlantphases(List plantphases) {
		this.plantphases = plantphases;
	}

}
