package org.cassava.model;
// Generated Nov 30, 2022, 10:33:28 PM by Hibernate Tools 5.5.9.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Province generated by hbm2java
 */
public class Province implements java.io.Serializable {

	private Integer provinceId;
	@JsonIgnore
	private Region region;
	private String name;
	private String nameEng;
	private String code;
	@JsonIgnore
	private List<District> districts = new ArrayList<District>();
	@JsonIgnore
	private List<PermissionProvince> permissionprovinces = new ArrayList<PermissionProvince>();

	public Province() {
	}

	public Province(String name) {
		this.name = name;
	}

	public Province(String name, String code, List districts, List permissionprovinces) {
		this.name = name;
		this.code = code;
		this.districts = districts;
		this.permissionprovinces = permissionprovinces;
	}
	
	public Province(Region region, String name, String nameEng, String code, List districts, List permissionprovinces) {
		this.region = region;
		this.name = name;
		this.nameEng = nameEng;
		this.code = code;
		this.districts = districts;
		this.permissionprovinces = permissionprovinces;
	}

	public Integer getProvinceId() {
		return this.provinceId;
	}

	public void setProvinceId(Integer provinceId) {
		this.provinceId = provinceId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public List<District> getDistricts() {
		return this.districts;
	}

	public void setDistricts(List districts) {
		this.districts = districts;
	}

	public List<PermissionProvince> getPermissionprovinces() {
		return this.permissionprovinces;
	}

	public void setPermissionprovinces(List permissionprovinces) {
		this.permissionprovinces = permissionprovinces;
	}

	public String getNameEng() {
		return nameEng;
	}

	public void setNameEng(String nameEng) {
		this.nameEng = nameEng;
	}

	public Region getRegion() {
		return region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}

}
