package org.cassava.model;
// Generated Jun 21, 2023, 7:48:27 PM by Hibernate Tools 6.1.3.Final

import java.sql.Timestamp;

/**
 * Refreshtoken generated by hbm2java
 */
public class Refreshtoken implements java.io.Serializable {

	private Integer refreshTokenId;
	private User user;
	private String token;
	private Timestamp expireDate;

	public Refreshtoken() {
	}

	public Refreshtoken(User user, String token, Timestamp expireDate) {
		this.user = user;
		this.token = token;
		this.expireDate = expireDate;
	}

	public Integer getRefreshTokenId() {
		return this.refreshTokenId;
	}

	public void setRefreshTokenId(Integer refreshTokenId) {
		this.refreshTokenId = refreshTokenId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public Timestamp getExpireDate() {
		return this.expireDate;
	}

	public void setExpireDate(Timestamp expireDate) {
		this.expireDate = expireDate;
	}

}
