package org.cassava.model;
// Generated Nov 30, 2022, 10:33:28 PM by Hibernate Tools 5.5.9.Final

import java.util.Date;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Registercode generated by hbm2java
 */
public class RegisterCode implements java.io.Serializable {

	private Integer registerCodeId;
	private Organization organization;
	private User user;
	@NotBlank(message = "ห้ามเว้นว่าง")
	@Size(min = 2, max = 20, message = "ชื่อต้องมีความยาวตั้งแต่ 2 - 20 ตัวอักษร")
	private String code;
	@NotNull(message = "ห้ามไม่มีค่า")
	private String userType;
	private int numUserPermit;
	@NotNull(message = "ห้ามไม่มีค่า")
	private int numUseRegist;
	@NotNull(message = "ห้ามไม่มีค่า")
	private Date startDate;
	@NotNull(message = "ห้ามไม่มีค่า")
	private Date expireDate;
	private Date createDate;

	public RegisterCode() {
	}

	public RegisterCode(Organization organization, String code, String userType, int numUserPermit, int numUseRegist,
			Date startDate, Date expireDate, Date createDate) {
		this.organization = organization;
		this.code = code;
		this.userType = userType;
		this.numUserPermit = numUserPermit;
		this.numUseRegist = numUseRegist;
		this.startDate = startDate;
		this.expireDate = expireDate;
		this.createDate = createDate;
	}

	public RegisterCode(Organization organization, User user, String code, String userType, int numUserPermit,
			int numUseRegist, Date startDate, Date expireDate, Date createDate) {
		this.organization = organization;
		this.user = user;
		this.code = code;
		this.userType = userType;
		this.numUserPermit = numUserPermit;
		this.numUseRegist = numUseRegist;
		this.startDate = startDate;
		this.expireDate = expireDate;
		this.createDate = createDate;
	}

	public Integer getRegisterCodeId() {
		return this.registerCodeId;
	}

	public void setRegisterCodeId(Integer registerCodeId) {
		this.registerCodeId = registerCodeId;
	}

	public Organization getOrganization() {
		return this.organization;
	}

	public void setOrganization(Organization organization) {
		this.organization = organization;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	public int getNumUserPermit() {
		return this.numUserPermit;
	}

	public void setNumUserPermit(int numUserPermit) {
		this.numUserPermit = numUserPermit;
	}

	public int getNumUseRegist() {
		return this.numUseRegist;
	}

	public void setNumUseRegist(int numUseRegist) {
		this.numUseRegist = numUseRegist;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getExpireDate() {
		return this.expireDate;
	}

	public void setExpireDate(Date expireDate) {
		this.expireDate = expireDate;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
