package org.cassava.model;
// Generated May 23, 2023, 10:56:11 PM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Region generated by hbm2java
 */
public class Region implements java.io.Serializable {

	private Integer regionId;
	private String name;
	private String nameEng;
	@JsonIgnore
	private List<Province> provinces = new ArrayList<Province>();

	public Region() {
	}

	public Region(String name, String nameEng) {
		this.name = name;
		this.nameEng = nameEng;
	}

	public Region(String name, String nameEng, List provinces) {
		this.name = name;
		this.nameEng = nameEng;
		this.provinces = provinces;
	}

	public Integer getRegionId() {
		return this.regionId;
	}

	public void setRegionId(Integer regionId) {
		this.regionId = regionId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNameEng() {
		return this.nameEng;
	}

	public void setNameEng(String nameEng) {
		this.nameEng = nameEng;
	}

	public List<Province> getProvinces() {
		return this.provinces;
	}

	public void setProvinces(List<Province> provinces) {
		this.provinces = provinces;
	}

}
