package org.cassava.model;
// Generated Nov 30, 2022, 10:33:28 PM by Hibernate Tools 5.5.9.Final

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Requestdetail generated by hbm2java
 */
public class RequestDetail implements java.io.Serializable {

	private Integer requestDetailId;
	private Request request;
	@JsonIgnore
	private Survey survey;
	private SurveyTarget surveyTarget;

	public RequestDetail() {
	}

	public RequestDetail(Request request, Survey survey, SurveyTarget surveyTarget) {
		this.request = request;
		this.survey = survey;
		this.surveyTarget = surveyTarget;
	}

	public Integer getRequestDetailId() {
		return this.requestDetailId;
	}

	public void setRequestDetailId(Integer requestDetailId) {
		this.requestDetailId = requestDetailId;
	}

	public Request getRequest() {
		return this.request;
	}

	public void setRequest(Request request) {
		this.request = request;
	}

	public Survey getSurvey() {
		return this.survey;
	}

	public void setSurvey(Survey survey) {
		this.survey = survey;
	}

	public SurveyTarget getSurveyTarget() {
		return surveyTarget;
	}

	public void setSurveyTarget(SurveyTarget surveyTarget) {
		this.surveyTarget = surveyTarget;
	}

}
