package org.cassava.model;
// Generated Nov 30, 2022, 10:33:28 PM by Hibernate Tools 5.5.9.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Subdistrict generated by hbm2java
 */
public class Subdistrict implements java.io.Serializable {

	private Integer subdistrictId;
	@JsonIgnore
	private District district;
	private String name;
	@JsonIgnore
	private List<Field> fields = new ArrayList<Field>();
	@JsonIgnore
	private List<Farmer> farmers = new ArrayList<Farmer>();

	public Subdistrict() {
	}

	public Subdistrict(District district, String name) {
		this.district = district;
		this.name = name;
	}

	public Subdistrict(District district, String name, List fields, List farmers) {
		this.district = district;
		this.name = name;
		this.fields = fields;
		this.farmers = farmers;
	}

	public Integer getSubdistrictId() {
		return this.subdistrictId;
	}

	public void setSubdistrictId(Integer subdistrictId) {
		this.subdistrictId = subdistrictId;
	}

	public District getDistrict() {
		return this.district;
	}

	public void setDistrict(District district) {
		this.district = district;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public List<Field> getFields() {
		return this.fields;
	}

	public void setFields(List fields) {
		this.fields = fields;
	}

	public List<Farmer> getFarmers() {
		return this.farmers;
	}

	public void setFarmers(List farmers) {
		this.farmers = farmers;
	}

}
