package org.cassava.model;
// Generated May 24, 2023, 8:55:59 AM by Hibernate Tools 5.6.3.Final

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Surveypoint generated by hbm2java
 */
public class SurveyPoint implements java.io.Serializable {

	private Integer surveyPointId;
	@JsonIgnore
	private Survey survey;
	private int pointNo;
	private String status;

	public SurveyPoint() {
	}

	public SurveyPoint(Survey survey, int pointNo, String status) {
		this.survey = survey;
		this.pointNo = pointNo;
		this.status = status;
	}

	public Integer getSurveyPointId() {
		return this.surveyPointId;
	}

	public void setSurveyPointId(Integer surveyPointId) {
		this.surveyPointId = surveyPointId;
	}

	public Survey getSurvey() {
		return this.survey;
	}

	public void setSurvey(Survey survey) {
		this.survey = survey;
	}

	public int getPointNo() {
		return this.pointNo;
	}

	public void setPointNo(int pointNo) {
		this.pointNo = pointNo;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
