package org.cassava.model;
// Generated Nov 30, 2022, 10:33:28 PM by Hibernate Tools 5.5.9.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Surveytarget generated by hbm2java
 */
public class SurveyTarget implements java.io.Serializable {

	private Integer surveyTargetId;
	@JsonIgnore
	private Survey survey;
	@JsonIgnore
	private TargetOfSurvey targetofsurvey;
	private Float avgDamageLevel;
	private Float percentDamage;
	@NotNull (message = "ห้ามไม่มีค่า")
	private String status;
	@JsonIgnore
	private List<SurveyTargetPoint> surveytargetpoints = new ArrayList<SurveyTargetPoint>();
	@JsonIgnore
	private List<RequestDetail> requestDetails = new ArrayList<RequestDetail>();

	public SurveyTarget() {
	}
	
	public void clone(SurveyTarget otherSurveyTarget) {
		this.avgDamageLevel = otherSurveyTarget.avgDamageLevel;
		this.percentDamage = otherSurveyTarget.percentDamage;
		this.status = otherSurveyTarget.status;
	}

	public SurveyTarget(Survey survey, TargetOfSurvey targetofsurvey, String status) {
		this.survey = survey;
		this.targetofsurvey = targetofsurvey;
		this.status = status;
	}

	public SurveyTarget(Survey survey, TargetOfSurvey targetofsurvey, Float avgDamageLevel, Float percentDamage,
			String status, List surveytargetpoints, List requestDetails) {
		this.survey = survey;
		this.targetofsurvey = targetofsurvey;
		this.avgDamageLevel = avgDamageLevel;
		this.percentDamage = percentDamage;
		this.status = status;
		this.surveytargetpoints = surveytargetpoints;
		this.requestDetails = requestDetails;
	}

	public Integer getSurveyTargetId() {
		return this.surveyTargetId;
	}

	public void setSurveyTargetId(Integer surveyTargetId) {
		this.surveyTargetId = surveyTargetId;
	}

	public Survey getSurvey() {
		return this.survey;
	}

	public void setSurvey(Survey survey) {
		this.survey = survey;
	}

	public TargetOfSurvey getTargetofsurvey() {
		return this.targetofsurvey;
	}

	public void setTargetofsurvey(TargetOfSurvey targetofsurvey) {
		this.targetofsurvey = targetofsurvey;
	}

	public Float getAvgDamageLevel() {
		return this.avgDamageLevel;
	}

	public void setAvgDamageLevel(Float avgDamageLevel) {
		this.avgDamageLevel = avgDamageLevel;
	}

	public Float getPercentDamage() {
		return this.percentDamage;
	}

	public void setPercentDamage(Float percentDamage) {
		this.percentDamage = percentDamage;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public List<SurveyTargetPoint> getSurveytargetpoints() {
		return this.surveytargetpoints;
	}

	public void setSurveytargetpoints(List surveytargetpoints) {
		this.surveytargetpoints = surveytargetpoints;
	}

	public List<RequestDetail> getRequestDetails() {
		return requestDetails;
	}

	public void setRequestDetails(List<RequestDetail> requestDetails) {
		this.requestDetails = requestDetails;
	}

	
}
