package org.cassava.model;
// Generated Nov 30, 2022, 10:33:28 PM by Hibernate Tools 5.5.9.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Targetofsurvey generated by hbm2java
 */
public class TargetOfSurvey implements java.io.Serializable {

	private Integer targetOfSurveyId;
	@NotBlank(message = "ห้ามเว้นว่าง")
	@Size(min = 2, max = 50, message = "ชื่อต้องมีความยาวตั้งแต่ 2 - 50 ตัวอักษร")
	private String name;
	@JsonIgnore
	private Disease disease;
	@JsonIgnore
	private List<PermissionTargetOfSurvey> permissiontargetofsurveys = new ArrayList<PermissionTargetOfSurvey>();
	@JsonIgnore
	private PestPhaseSurvey pestphasesurvey;
	@JsonIgnore
	private List<SurveyTarget> surveytargets = new ArrayList<SurveyTarget>();
	@JsonIgnore
	private NaturalEnemy naturalenemy;

	public TargetOfSurvey() {
	}

	public TargetOfSurvey(String name) {
		this.name = name;
	}

	public TargetOfSurvey(String name, Disease disease,List<PermissionTargetOfSurvey> permissiontargetofsurveys, PestPhaseSurvey pestphasesurvey, List<SurveyTarget> surveytargets,
			NaturalEnemy naturalenemy) {
		this.name = name;
		this.disease = disease;
		this.permissiontargetofsurveys = permissiontargetofsurveys;
		this.pestphasesurvey = pestphasesurvey;
		this.surveytargets = surveytargets;
		this.naturalenemy = naturalenemy;
	}

	public Integer getTargetOfSurveyId() {
		return this.targetOfSurveyId;
	}

	public void setTargetOfSurveyId(Integer targetOfSurveyId) {
		this.targetOfSurveyId = targetOfSurveyId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Disease getDisease() {
		return this.disease;
	}

	public void setDisease(Disease disease) {
		this.disease = disease;
	}
	
	public List<PermissionTargetOfSurvey> getPermissiontargetofsurveys() {
		return this.permissiontargetofsurveys;
	}

	public void setPermissiontargetofsurveys(List<PermissionTargetOfSurvey> permissiontargetofsurveys) {
		this.permissiontargetofsurveys = permissiontargetofsurveys;
	}

	public PestPhaseSurvey getPestphasesurvey() {
		return this.pestphasesurvey;
	}

	public void setPestphasesurvey(PestPhaseSurvey pestphasesurvey) {
		this.pestphasesurvey = pestphasesurvey;
	}

	public List<SurveyTarget> getSurveytargets() {
		return this.surveytargets;
	}

	public void setSurveytargets(List surveytargets) {
		this.surveytargets = surveytargets;
	}

	public NaturalEnemy getNaturalenemy() {
		return this.naturalenemy;
	}

	public void setNaturalenemy(NaturalEnemy naturalenemy) {
		this.naturalenemy = naturalenemy;
	}

}
