package org.cassava.model;
// Generated Nov 30, 2022, 10:33:28 PM by Hibernate Tools 5.5.9.Final

/**
 * Token generated by hbm2java
 */
public class Token implements java.io.Serializable {

	private Integer tokenId;
	private Staff staff;
	private int value;
	private int expireDate;

	public Token() {
	}

	public Token(Staff staff, int value, int expireDate) {
		this.staff = staff;
		this.value = value;
		this.expireDate = expireDate;
	}

	public Integer getTokenId() {
		return this.tokenId;
	}

	public void setTokenId(Integer tokenId) {
		this.tokenId = tokenId;
	}

	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	public int getValue() {
		return this.value;
	}

	public void setValue(int value) {
		this.value = value;
	}

	public int getExpireDate() {
		return this.expireDate;
	}

	public void setExpireDate(int expireDate) {
		this.expireDate = expireDate;
	}

}
