package org.cassava.model;
// Generated Nov 30, 2022, 10:33:28 PM by Hibernate Tools 5.5.9.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;
import javax.validation.constraints.Digits;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer userId;
	@JsonIgnore
	private String username;
	
	@NotBlank(message = "ห้ามเว้นว่าง")
	@Size(min = 2, max = 10, message = "ต้องมีความยาวตั้งแต่ 2 - 10 ตัวอักษร")
	private String title;
	
	@NotBlank(message = "ห้ามเว้นว่าง")
	@Size(min = 2, max = 20, message = "ต้องมีความยาวตั้งแต่ 2 - 20 ตัวอักษร")
	private String firstName;
	
	@NotBlank(message = "ห้ามเว้นว่าง")
	@Size(min = 2, max = 30, message = "ต้องมีความยาวตั้งแต่ 2 - 30 ตัวอักษร")
	private String lastName;
	
	@Digits(message="ตัวเลขควรมี 10 หลัก", fraction = 0, integer = 10)
	private String phoneNo;
	@NotNull (message = "ห้ามไม่มีค่า")
	private String userStatus;
	private Date latestLogin;
	private String requestInfoStatus;
	@JsonIgnore
	private List<Planting> plantingsForCreateBy = new ArrayList<Planting>();
	@JsonIgnore
	private List<Survey> surveysForLastUpdateBy = new ArrayList<Survey>();
	@JsonIgnore
	private List<Survey> surveysForCreateBy = new ArrayList<Survey>();
	@JsonIgnore
	private List<Message> messages = new ArrayList<Message>();
	@JsonIgnore
	private List<Field> fieldsForLastUpdateBy = new ArrayList<Field>();
	@JsonIgnore
	private List<Field> fieldsForCreateBy = new ArrayList<Field>();
	@JsonIgnore
	private List<UserInField> userinfields = new ArrayList<UserInField>();
	@JsonIgnore
	private List<ImgSurveyTargetPoint> imgsurveytargetpointsForApproveBy = new ArrayList<ImgSurveyTargetPoint>();
	@JsonIgnore
	private List<Messagereceiver> messagereceivers = new ArrayList<Messagereceiver>();
	@JsonIgnore
	private List<ImgSurveyTargetPoint> imgsurveytargetpointsForUploadBy = new ArrayList<ImgSurveyTargetPoint>();
	@JsonIgnore
	private Farmer farmer;
	@JsonIgnore
	private List<ImgHerbicideDamage> imgherbicidedamagesForUploadBy = new ArrayList<ImgHerbicideDamage>();
	@JsonIgnore
	private List<Survey> surveysForImgOwner = new ArrayList<Survey>();
	@JsonIgnore
	private List<Role> roles = new ArrayList<Role>();
	@JsonIgnore
	private List<ImgHerbicideDamage> imgherbicidedamagesForApproveBy = new ArrayList<ImgHerbicideDamage>();
	@JsonIgnore
	private List<Planting> plantingsForLastUpdateBy = new ArrayList<Planting>();
	@JsonIgnore
	private List<RegisterCode> registercodes = new ArrayList<RegisterCode>();
	@JsonIgnore
	private Staff staff;
	@JsonIgnore
	private List<Survey> surveysForImgPhotographer = new ArrayList<Survey>();

	public User() {
	}

	public User(String firstName, String lastName, String phoneNo, String userStatus, String requestInfoStatus) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.phoneNo = phoneNo;
		this.userStatus = userStatus;
		this.requestInfoStatus = requestInfoStatus;
	}
	
	public User(String username, String title, String firstName, String lastName, String phoneNo, String userStatus,Date latestLogin,String requestInfoStatus) {
		this.username = username;
		this.title = title;
		this.firstName = firstName;
		this.lastName = lastName;
		this.phoneNo = phoneNo;
		this.userStatus = userStatus;
		this.latestLogin = latestLogin;
		this.requestInfoStatus = requestInfoStatus;
	}

	public User(String username, String title, String firstName, String lastName, String phoneNo, String userStatus,
			Date latestLogin, String requestInfoStatus, List plantingsForCreateBy, List surveysForLastUpdateBy,
			List surveysForCreateBy, List messages, List fieldsForLastUpdateBy, List fieldsForCreateBy, List userinfields,
			List imgsurveytargetpointsForApproveBy, List messagereceivers, List imgsurveytargetpointsForUploadBy,
			Farmer farmer, List imgherbicidedamagesForUploadBy, List surveysForImgOwner, List roles,
			List imgherbicidedamagesForApproveBy, List plantingsForLastUpdateBy, List registercodes, Staff staff,
			List surveysForImgPhotographer) {
		this.username = username;
		this.title = title;
		this.firstName = firstName;
		this.lastName = lastName;
		this.phoneNo = phoneNo;
		this.userStatus = userStatus;
		this.latestLogin = latestLogin;
		this.requestInfoStatus = requestInfoStatus;
		this.plantingsForCreateBy = plantingsForCreateBy;
		this.surveysForLastUpdateBy = surveysForLastUpdateBy;
		this.surveysForCreateBy = surveysForCreateBy;
		this.messages = messages;
		this.fieldsForLastUpdateBy = fieldsForLastUpdateBy;
		this.fieldsForCreateBy = fieldsForCreateBy;
		this.userinfields = userinfields;
		this.imgsurveytargetpointsForApproveBy = imgsurveytargetpointsForApproveBy;
		this.messagereceivers = messagereceivers;
		this.imgsurveytargetpointsForUploadBy = imgsurveytargetpointsForUploadBy;
		this.farmer = farmer;
		this.imgherbicidedamagesForUploadBy = imgherbicidedamagesForUploadBy;
		this.surveysForImgOwner = surveysForImgOwner;
		this.roles = roles;
		this.imgherbicidedamagesForApproveBy = imgherbicidedamagesForApproveBy;
		this.plantingsForLastUpdateBy = plantingsForLastUpdateBy;
		this.registercodes = registercodes;
		this.staff = staff;
		this.surveysForImgPhotographer = surveysForImgPhotographer;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}

	public String getUserStatus() {
		return this.userStatus;
	}

	public void setUserStatus(String userStatus) {
		this.userStatus = userStatus;
	}

	public Date getLatestLogin() {
		return this.latestLogin;
	}

	public void setLatestLogin(Date latestLogin) {
		this.latestLogin = latestLogin;
	}

	public String getRequestInfoStatus() {
		return this.requestInfoStatus;
	}

	public void setRequestInfoStatus(String requestInfoStatus) {
		this.requestInfoStatus = requestInfoStatus;
	}

	

	public Farmer getFarmer() {
		return this.farmer;
	}

	public void setFarmer(Farmer farmer) {
		this.farmer = farmer;
	}

	

	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	public List<Planting> getPlantingsForCreateBy() {
		return plantingsForCreateBy;
	}

	public void setPlantingsForCreateBy(List<Planting> plantingsForCreateBy) {
		this.plantingsForCreateBy = plantingsForCreateBy;
	}

	public List<Survey> getSurveysForLastUpdateBy() {
		return surveysForLastUpdateBy;
	}

	public void setSurveysForLastUpdateBy(List<Survey> surveysForLastUpdateBy) {
		this.surveysForLastUpdateBy = surveysForLastUpdateBy;
	}

	public List<Survey> getSurveysForCreateBy() {
		return surveysForCreateBy;
	}

	public void setSurveysForCreateBy(List<Survey> surveysForCreateBy) {
		this.surveysForCreateBy = surveysForCreateBy;
	}

	public List<Field> getFieldsForLastUpdateBy() {
		return fieldsForLastUpdateBy;
	}

	public void setFieldsForLastUpdateBy(List<Field> fieldsForLastUpdateBy) {
		this.fieldsForLastUpdateBy = fieldsForLastUpdateBy;
	}

	public List<Message> getMessages() {
		return messages;
	}

	public void setMessages(List<Message> messages) {
		this.messages = messages;
	}

	public List<Field> getFieldsForCreateBy() {
		return fieldsForCreateBy;
	}

	public void setFieldsForCreateBy(List<Field> fieldsForCreateBy) {
		this.fieldsForCreateBy = fieldsForCreateBy;
	}

	public List<UserInField> getUserinfields() {
		return userinfields;
	}

	public void setUserinfields(List<UserInField> userinfields) {
		this.userinfields = userinfields;
	}

	public List<Messagereceiver> getMessagereceivers() {
		return messagereceivers;
	}

	public void setMessagereceivers(List<Messagereceiver> messagereceivers) {
		this.messagereceivers = messagereceivers;
	}

	public List<ImgSurveyTargetPoint> getImgsurveytargetpointsForApproveBy() {
		return imgsurveytargetpointsForApproveBy;
	}

	public void setImgsurveytargetpointsForApproveBy(List<ImgSurveyTargetPoint> imgsurveytargetpointsForApproveBy) {
		this.imgsurveytargetpointsForApproveBy = imgsurveytargetpointsForApproveBy;
	}

	public List<ImgHerbicideDamage> getImgherbicidedamagesForUploadBy() {
		return imgherbicidedamagesForUploadBy;
	}

	public void setImgherbicidedamagesForUploadBy(List<ImgHerbicideDamage> imgherbicidedamagesForUploadBy) {
		this.imgherbicidedamagesForUploadBy = imgherbicidedamagesForUploadBy;
	}

	public List<ImgSurveyTargetPoint> getImgsurveytargetpointsForUploadBy() {
		return imgsurveytargetpointsForUploadBy;
	}

	public void setImgsurveytargetpointsForUploadBy(List<ImgSurveyTargetPoint> imgsurveytargetpointsForUploadBy) {
		this.imgsurveytargetpointsForUploadBy = imgsurveytargetpointsForUploadBy;
	}

	public List<Survey> getSurveysForImgOwner() {
		return surveysForImgOwner;
	}

	public void setSurveysForImgOwner(List<Survey> surveysForImgOwner) {
		this.surveysForImgOwner = surveysForImgOwner;
	}

	public List<Role> getRoles() {
		return roles;
	}

	public void setRoles(List<Role> roles) {
		this.roles = roles;
	}

	public List<Planting> getPlantingsForLastUpdateBy() {
		return plantingsForLastUpdateBy;
	}

	public void setPlantingsForLastUpdateBy(List<Planting> plantingsForLastUpdateBy) {
		this.plantingsForLastUpdateBy = plantingsForLastUpdateBy;
	}

	public List<ImgHerbicideDamage> getImgherbicidedamagesForApproveBy() {
		return imgherbicidedamagesForApproveBy;
	}

	public void setImgherbicidedamagesForApproveBy(List<ImgHerbicideDamage> imgherbicidedamagesForApproveBy) {
		this.imgherbicidedamagesForApproveBy = imgherbicidedamagesForApproveBy;
	}

	public List<Survey> getSurveysForImgPhotographer() {
		return surveysForImgPhotographer;
	}

	public void setSurveysForImgPhotographer(List<Survey> surveysForImgPhotographer) {
		this.surveysForImgPhotographer = surveysForImgPhotographer;
	}

	public List<RegisterCode> getRegistercodes() {
		return registercodes;
	}

	public void setRegistercodes(List<RegisterCode> registercodes) {
		this.registercodes = registercodes;
	}

	

}
