package project.soa.boardgame.cafe.boardgamecafe.model;
// Generated Mar 16, 2023, 3:22:57 AM by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Boardgame generated by hbm2java
 */
public class Boardgame implements java.io.Serializable {

	private Integer boardgameId;
	private String description;
	private int playtime;
	private int age;
	private int number;
	private String type;
	private float price;
	private String name;
	private String imgPath;
	private Set boardgameRenteds = new HashSet(0);
	private Set reservedGameboards = new HashSet(0);
	private Set boardgameBoughts = new HashSet(0);

	public Boardgame() {
	}

	public Boardgame(String description, int playtime, int age, int number, String type, float price, String name) {
		this.description = description;
		this.playtime = playtime;
		this.age = age;
		this.number = number;
		this.type = type;
		this.price = price;
		this.name = name;
	}

	public Boardgame(String description, int playtime, int age, int number, String type, float price, String name,
			String imgPath, Set boardgamerenteds, Set reservedgameboards, Set boardgameboughts) {
		this.description = description;
		this.playtime = playtime;
		this.age = age;
		this.number = number;
		this.type = type;
		this.price = price;
		this.name = name;
		this.imgPath = imgPath;
		this.boardgameRenteds = boardgamerenteds;
		this.reservedGameboards = reservedgameboards;
		this.boardgameBoughts = boardgameboughts;
	}

	public Integer getBoardgameId() {
		return this.boardgameId;
	}

	public void setBoardgameId(Integer boardgameId) {
		this.boardgameId = boardgameId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getPlaytime() {
		return this.playtime;
	}

	public void setPlaytime(int playtime) {
		this.playtime = playtime;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public int getNumber() {
		return this.number;
	}

	public void setNumber(int number) {
		this.number = number;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getImgPath() {
		return this.imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

	public Set getBoardgameRenteds() {
		return this.boardgameRenteds;
	}

	public void setBoardgameRenteds(Set boardgamerenteds) {
		this.boardgameRenteds = boardgamerenteds;
	}

	public Set getReservedGameboards() {
		return this.reservedGameboards;
	}

	public void setReservedGameboards(Set reservedgameboards) {
		this.reservedGameboards = reservedgameboards;
	}

	public Set getBoardgameBoughts() {
		return this.boardgameBoughts;
	}

	public void setBoardgameBoughts(Set boardgameboughts) {
		this.boardgameBoughts = boardgameboughts;
	}

}
