package project.soa.boardgame.cafe.boardgamecafe.model;
// Generated Mar 16, 2023, 3:22:57 AM by Hibernate Tools 5.6.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Booking generated by hbm2java
 */
public class Booking implements java.io.Serializable {

	private Integer bookingId;
	private Table table;
	private User user;
	private int numberbooking;
	private Date date;
	private Date timeStart;
	private Date timeEnd;
	private String name;
	private String note;
	private String tel;
	private Set reservedGameboards = new HashSet(0);

	public Booking() {
	}

	public Booking(Table table, User user, int numberbooking, Date date, String name, String note, String tel) {
		this.table = table;
		this.user = user;
		this.numberbooking = numberbooking;
		this.date = date;
		this.name = name;
		this.note = note;
		this.tel = tel;
	}

	public Booking(Table table, User user, int numberbooking, Date date, Date timeStart, Date timeEnd, String name,
			String note, String tel, Set reservedgameboards) {
		this.table = table;
		this.user = user;
		this.numberbooking = numberbooking;
		this.date = date;
		this.timeStart = timeStart;
		this.timeEnd = timeEnd;
		this.name = name;
		this.note = note;
		this.tel = tel;
		this.reservedGameboards = reservedgameboards;
	}

	public Integer getBookingId() {
		return this.bookingId;
	}

	public void setBookingId(Integer bookingId) {
		this.bookingId = bookingId;
	}

	public Table getTable() {
		return this.table;
	}

	public void setTable(Table table) {
		this.table = table;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public int getNumberbooking() {
		return this.numberbooking;
	}

	public void setNumberbooking(int numberbooking) {
		this.numberbooking = numberbooking;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Date getTimeStart() {
		return this.timeStart;
	}

	public void setTimeStart(Date timeStart) {
		this.timeStart = timeStart;
	}

	public Date getTimeEnd() {
		return this.timeEnd;
	}

	public void setTimeEnd(Date timeEnd) {
		this.timeEnd = timeEnd;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public Set getReservedGameboards() {
		return this.reservedGameboards;
	}

	public void setReservedGameboards(Set reservedgameboards) {
		this.reservedGameboards = reservedgameboards;
	}

}
