package project.soa.boardgame.cafe.boardgamecafe.model;
// Generated Mar 16, 2023, 3:22:57 AM by Hibernate Tools 5.6.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Buyboardgame generated by hbm2java
 */
public class BuyBoardgame implements java.io.Serializable {

	private Integer buyboardgameId;
	private User user;
	private Date date;
	private String address;
	private String name;
	private String type;
	private String tel;
	private String transferslip;
	private Set boardgameBoughts = new HashSet(0);

	public BuyBoardgame() {
	}

	public BuyBoardgame(User user, Date date, String address, String name, String type, String tel,
			String transferslip) {
		this.user = user;
		this.date = date;
		this.address = address;
		this.name = name;
		this.type = type;
		this.tel = tel;
		this.transferslip = transferslip;
	}

	public BuyBoardgame(User user, Date date, String address, String name, String type, String tel, String transferslip,
			Set boardgameboughts) {
		this.user = user;
		this.date = date;
		this.address = address;
		this.name = name;
		this.type = type;
		this.tel = tel;
		this.transferslip = transferslip;
		this.boardgameBoughts = boardgameboughts;
	}

	public Integer getBuyboardgameId() {
		return this.buyboardgameId;
	}

	public void setBuyboardgameId(Integer buyboardgameId) {
		this.buyboardgameId = buyboardgameId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getTransferslip() {
		return this.transferslip;
	}

	public void setTransferslip(String transferslip) {
		this.transferslip = transferslip;
	}

	public Set getBoardgameBoughts() {
		return this.boardgameBoughts;
	}

	public void setBoardgameBoughts(Set boardgameboughts) {
		this.boardgameBoughts = boardgameboughts;
	}

}
