package project.soa.boardgame.cafe.boardgamecafe.model;
// Generated Mar 16, 2023, 3:22:57 AM by Hibernate Tools 5.6.3.Final

/**
 * Manubooking generated by hbm2java
 */
public class ManuBooking implements java.io.Serializable {

	private Integer manubookingId;
	private Menu menu;
	private User user;

	public ManuBooking() {
	}

	public ManuBooking(Menu menu, User user) {
		this.menu = menu;
		this.user = user;
	}

	public Integer getManubookingId() {
		return this.manubookingId;
	}

	public void setManubookingId(Integer manubookingId) {
		this.manubookingId = manubookingId;
	}

	public Menu getMenu() {
		return this.menu;
	}

	public void setMenu(Menu menu) {
		this.menu = menu;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
