package project.soa.boardgame.cafe.boardgamecafe.model;
// Generated Mar 16, 2023, 3:22:57 AM by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Menu generated by hbm2java
 */
public class Menu implements java.io.Serializable {

	private Integer menuId;
	private String name;
	private float price;
	private String type;
	private String imgPath;
	private Set manuBookings = new HashSet(0);

	public Menu() {
	}

	public Menu(String name, float price, String type) {
		this.name = name;
		this.price = price;
		this.type = type;
	}

	public Menu(String name, float price, String type, String imgPath, Set manubookings) {
		this.name = name;
		this.price = price;
		this.type = type;
		this.imgPath = imgPath;
		this.manuBookings = manubookings;
	}

	public Integer getMenuId() {
		return this.menuId;
	}

	public void setMenuId(Integer menuId) {
		this.menuId = menuId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getImgPath() {
		return this.imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

	public Set getManuBookings() {
		return this.manuBookings;
	}

	public void setManuBookings(Set manubookings) {
		this.manuBookings = manubookings;
	}

}
