package project.soa.boardgame.cafe.boardgamecafe.model;
// Generated Mar 16, 2023, 3:22:57 AM by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Table generated by hbm2java
 */
public class Table implements java.io.Serializable {

	private Integer tableId;
	private String status;
	private int number;
	private Set bookings = new HashSet(0);

	public Table() {
	}

	public Table(String status, int number) {
		this.status = status;
		this.number = number;
	}

	public Table(String status, int number, Set bookings) {
		this.status = status;
		this.number = number;
		this.bookings = bookings;
	}

	public Integer getTableId() {
		return this.tableId;
	}

	public void setTableId(Integer tableId) {
		this.tableId = tableId;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public int getNumber() {
		return this.number;
	}

	public void setNumber(int number) {
		this.number = number;
	}

	public Set getBookings() {
		return this.bookings;
	}

	public void setBookings(Set bookings) {
		this.bookings = bookings;
	}

}
