package project.soa.boardgame.cafe.boardgamecafe.model;
// Generated Mar 16, 2023, 3:22:57 AM by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer userId;
	private String firstname;
	private String phonenumber;
	private String address;
	private String lastname;
	private String username;
	private String password;
	private Set bookings = new HashSet(0);
	private Set manuBookings = new HashSet(0);
	private Set boardgameRentals = new HashSet(0);
	private Set buyBoardgames = new HashSet(0);

	public User() {
	}

	public User(String firstname, String phonenumber, String address, String lastname, String username,
			String password) {
		this.firstname = firstname;
		this.phonenumber = phonenumber;
		this.address = address;
		this.lastname = lastname;
		this.username = username;
		this.password = password;
	}

	public User(String firstname, String phonenumber, String address, String lastname, String username, String password,
			Set bookings, Set manubookings, Set boardgamerentals, Set buyboardgames) {
		this.firstname = firstname;
		this.phonenumber = phonenumber;
		this.address = address;
		this.lastname = lastname;
		this.username = username;
		this.password = password;
		this.bookings = bookings;
		this.manuBookings = manubookings;
		this.boardgameRentals = boardgamerentals;
		this.buyBoardgames = buyboardgames;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getPhonenumber() {
		return this.phonenumber;
	}

	public void setPhonenumber(String phonenumber) {
		this.phonenumber = phonenumber;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set getBookings() {
		return this.bookings;
	}

	public void setBookings(Set bookings) {
		this.bookings = bookings;
	}

	public Set getManuBookings() {
		return this.manuBookings;
	}

	public void setManuBookings(Set manubookings) {
		this.manuBookings = manubookings;
	}

	public Set getBoardgameRentals() {
		return this.boardgameRentals;
	}

	public void setBoardgameRentals(Set boardgamerentals) {
		this.boardgameRentals = boardgamerentals;
	}

	public Set getBuyBoardgames() {
		return this.buyBoardgames;
	}

	public void setBuyBoardgames(Set buyboardgames) {
		this.buyBoardgames = buyboardgames;
	}

}
