package ku.kps.ds.som.kukpssom.model;
// Generated Sep 29, 2023, 10:57:05 PM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Menu generated by hbm2java
 */
public class Menu implements java.io.Serializable {

	private Integer menuId;
	private Store store;
	private String name;
	private int price;
	private List<MenuInOrder> menuInOrders = new ArrayList<MenuInOrder>();

	public Menu() {
	}

	public Menu(Store store, String name, int price) {
		this.store = store;
		this.name = name;
		this.price = price;
	}

	public Menu(Store store, String name, int price, List<MenuInOrder> menuInOrders) {
		this.store = store;
		this.name = name;
		this.price = price;
		this.setMenuInOrders(menuInOrders);
	}

	public Integer getMenuId() {
		return this.menuId;
	}

	public void setMenuId(Integer menuId) {
		this.menuId = menuId;
	}

	public Store getStore() {
		return this.store;
	}

	public void setStore(Store store) {
		this.store = store;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	public List<MenuInOrder> getMenuInOrders() {
		return menuInOrders;
	}

	public void setMenuInOrders(List<MenuInOrder> menuInOrders) {
		this.menuInOrders = menuInOrders;
	}

}
