package ku.kps.ds.som.kukpssom.model;
// Generated Sep 29, 2023, 10:57:05 PM by Hibernate Tools 5.6.3.Final

/**
 * Menuinorder generated by hbm2java
 */
public class MenuInOrder implements java.io.Serializable {

	private Integer menuInOrder;
	private Menu menu;
	private OrderFood orderFood;
	private int price;
	private String level;
	private String addOn;

	public MenuInOrder() {
	}

	public MenuInOrder(Menu menu, OrderFood orderFood, int price, String level, String addOn) {
		this.menu = menu;
		this.orderFood = orderFood;
		this.price = price;
		this.level = level;
		this.addOn = addOn;
	}

	public Integer getMenuInOrder() {
		return this.menuInOrder;
	}

	public void setMenuInOrder(Integer menuInOrder) {
		this.menuInOrder = menuInOrder;
	}

	public Menu getMenu() {
		return this.menu;
	}

	public void setMenu(Menu menu) {
		this.menu = menu;
	}

	public OrderFood getOrderFood() {
		return this.orderFood;
	}

	public void setOrderFood(OrderFood orderFood) {
		this.orderFood = orderFood;
	}

	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	public String getAddOn() {
		return this.addOn;
	}

	public void setAddOn(String addOn) {
		this.addOn = addOn;
	}

}
