package ku.kps.ds.som.kukpssom.model;
// Generated Oct 4, 2023, 9:05:57 PM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * OrderFood generated by hbm2java
 */
public class OrderFood implements java.io.Serializable {

	private Integer orderId;
	private User user;
	private int storeId;
	private String orderCode;
	private String status;
	private Date date;
	private Date time;
	private int price;
	private int timeCount;
	private String note;
	private List<MenuInOrder> menuInOrders = new ArrayList<MenuInOrder>();
	private List<QueueOrder> queueOrders = new ArrayList<QueueOrder>();

	public OrderFood() {
	}

	public OrderFood(User user, int storeId, String orderCode, String status, Date date, int price, int timeCount,
			String note) {
		this.user = user;
		this.storeId = storeId;
		this.orderCode = orderCode;
		this.status = status;
		this.date = date;
		this.price = price;
		this.timeCount = timeCount;
		this.note = note;
	}

	public OrderFood(User user, int storeId, String orderCode, String status, Date date, Date time, int price,
			int timeCount, String note, List<MenuInOrder> menuInOrders, List<QueueOrder> queueOrders) {
		this.user = user;
		this.storeId = storeId;
		this.orderCode = orderCode;
		this.status = status;
		this.date = date;
		this.time = time;
		this.price = price;
		this.timeCount = timeCount;
		this.note = note;
		this.setMenuInOrders(menuInOrders);
		this.setQueueOrders(queueOrders);
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public int getStoreId() {
		return this.storeId;
	}

	public void setStoreId(int storeId) {
		this.storeId = storeId;
	}

	public String getOrderCode() {
		return this.orderCode;
	}

	public void setOrderCode(String orderCode) {
		this.orderCode = orderCode;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	public int getTimeCount() {
		return this.timeCount;
	}

	public void setTimeCount(int timeCount) {
		this.timeCount = timeCount;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public List<MenuInOrder> getMenuInOrders() {
		return menuInOrders;
	}

	public void setMenuInOrders(List<MenuInOrder> menuInOrders) {
		this.menuInOrders = menuInOrders;
	}

	public List<QueueOrder> getQueueOrders() {
		return queueOrders;
	}

	public void setQueueOrders(List<QueueOrder> queueOrders) {
		this.queueOrders = queueOrders;
	}



}
