package ku.kps.ds.som.kukpssom.model;
// Generated Sep 29, 2023, 10:57:05 PM by Hibernate Tools 5.6.3.Final

import java.util.Date;

/**
 * Queueorder generated by hbm2java
 */
public class QueueOrder implements java.io.Serializable {

	private Integer queueOrderId;
	private OrderFood orderFood;
	private int orderNumber;
	private Date time;
	private int timeCount;
	private String orderCode;

	public QueueOrder() {
	}

	public QueueOrder(OrderFood orderFood, int orderNumber, int timeCount, String orderCode) {
		this.setOrderFood(orderFood);
		this.orderNumber = orderNumber;
		this.timeCount = timeCount;
		this.orderCode = orderCode;
	}

	public QueueOrder(OrderFood orderFood, int orderNumber, Date time, int timeCount, String orderCode) {
		this.setOrderFood(orderFood);
		this.orderNumber = orderNumber;
		this.time = time;
		this.timeCount = timeCount;
		this.orderCode = orderCode;
	}

	public Integer getQueueOrderId() {
		return this.queueOrderId;
	}

	public void setQueueOrderId(Integer queueOrderId) {
		this.queueOrderId = queueOrderId;
	}

	public int getOrderNumber() {
		return this.orderNumber;
	}

	public void setOrderNumber(int orderNumber) {
		this.orderNumber = orderNumber;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public int getTimeCount() {
		return this.timeCount;
	}

	public void setTimeCount(int timeCount) {
		this.timeCount = timeCount;
	}

	public String getOrderCode() {
		return this.orderCode;
	}

	public void setOrderCode(String orderCode) {
		this.orderCode = orderCode;
	}

	public OrderFood getOrderFood() {
		return orderFood;
	}

	public void setOrderFood(OrderFood orderFood) {
		this.orderFood = orderFood;
	}

}
