package ku.kps.ds.som.kukpssom.model;
// Generated Oct 28, 2023, 10:09:23 PM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Store generated by hbm2java
 */
public class Store implements java.io.Serializable {

	private Integer storeId;
	private User user;
	private String name;
	private String timeOpen;
	private String timeClose;
	private String status;
	private String type;
	private List<Menu> menus = new ArrayList<Menu>();

	public Store() {
	}

	public Store(User user, String name, String timeOpen, String timeClose, String status, String type) {
		this.user = user;
		this.name = name;
		this.timeOpen = timeOpen;
		this.timeClose = timeClose;
		this.status = status;
		this.type = type;
	}

	public Store(User user, String name, String timeOpen, String timeClose, String status, String type, List<Menu> menus) {
		this.user = user;
		this.name = name;
		this.timeOpen = timeOpen;
		this.timeClose = timeClose;
		this.status = status;
		this.type = type;
		this.setMenus(menus);
	}

	public Integer getStoreId() {
		return this.storeId;
	}

	public void setStoreId(Integer storeId) {
		this.storeId = storeId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTimeOpen() {
		return this.timeOpen;
	}

	public void setTimeOpen(String timeOpen) {
		this.timeOpen = timeOpen;
	}

	public String getTimeClose() {
		return this.timeClose;
	}

	public void setTimeClose(String timeClose) {
		this.timeClose = timeClose;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public List<Menu> getMenus() {
		return menus;
	}

	public void setMenus(List<Menu> menus) {
		this.menus = menus;
	}

	

}
