package ku.kps.ds.som.kukpssom.model;
// Generated Sep 29, 2023, 11:31:16 PM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer userId;
	private String username;
	private String password;
	private String name;
	private String suename;
	private String role;
	private List<Store> stores = new ArrayList<Store>();
	private List<OrderFood> orderFoods = new ArrayList<OrderFood>();

	public User() {
	}

	public User(String username, String password, String name, String suename, String role) {
		this.username = username;
		this.password = password;
		this.name = name;
		this.suename = suename;
		this.role = role;
	}

	public User(String username, String password, String name, String suename, String role, List<Store> stores,
			List<OrderFood> orderFoods) {
		this.username = username;
		this.password = password;
		this.name = name;
		this.suename = suename;
		this.role = role;
		this.stores = stores;
		this.orderFoods = orderFoods;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSuename() {
		return this.suename;
	}

	public void setSuename(String suename) {
		this.suename = suename;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public List<Store> getStores() {
		return this.stores;
	}

	public void setStores(List<Store> stores) {
		this.stores = stores;
	}

	public List<OrderFood> getOrderFoods() {
		return this.orderFoods;
	}

	public void setOrderFoods(List<OrderFood> orderFoods) {
		this.orderFoods = orderFoods;
	}

}
